// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"uuid"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AuthType.
const (
	Enrol     AuthType = "enrol"
	Self      AuthType = "self"
	Signature AuthType = "signature"
)

// Valid indicates whether the value is a known member of the AuthType enum.
func (e AuthType) Valid() bool {
	switch e {
	case Enrol:
		return true
	case Self:
		return true
	case Signature:
		return true
	default:
		return false
	}
}

// Defines values for Tier.
const (
	Hardware Tier = "hardware"
	Software Tier = "software"
	Tee      Tier = "tee"
)

// Valid indicates whether the value is a known member of the Tier enum.
func (e Tier) Valid() bool {
	switch e {
	case Hardware:
		return true
	case Software:
		return true
	case Tee:
		return true
	default:
		return false
	}
}

// AuthType signature: Ed25519 by the identity key; enrol: HMAC from the QR secret; self:
// HMAC from the device's own ECDH (docs/crypto.md, Wraps).
type AuthType string

// Device defines model for Device.
type Device struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        UUID      `json:"id"`
	PublicKey []byte    `json:"publicKey"`
	Tier      Tier      `json:"tier"`
}

// DeviceInput defines model for DeviceInput.
type DeviceInput struct {
	// PublicKey 65-byte uncompressed point on the glowie curve
	PublicKey []byte `json:"publicKey"`
	Tier      Tier   `json:"tier"`
}

// DeviceList defines model for DeviceList.
type DeviceList struct {
	Devices []Device `json:"devices"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// IdentityKey defines model for IdentityKey.
type IdentityKey struct {
	// PublicKey Ed25519
	PublicKey []byte `json:"publicKey"`
}

// KeyRotation defines model for KeyRotation.
type KeyRotation struct {
	NewVersion int            `json:"newVersion"`
	Wraps      []RotationWrap `json:"wraps"`
}

// Me defines model for Me.
type Me struct {
	Devices []Device `json:"devices"`
	Id      UUID     `json:"id"`

	// IdentityPublicKey Ed25519
	IdentityPublicKey *[]byte `json:"identityPublicKey,omitempty"`

	// KeyVersion Current version of the practice key
	KeyVersion int `json:"keyVersion"`
}

// OldKeyError defines model for OldKeyError.
type OldKeyError struct {
	CurrentKeyVersion int    `json:"currentKeyVersion"`
	Error             string `json:"error"`
}

// PracticeLog defines model for PracticeLog.
type PracticeLog struct {
	DeletedAt  *time.Time `json:"deletedAt,omitempty"`
	Id         UUID       `json:"id"`
	KeyVersion int        `json:"keyVersion"`
	Sealed     *[]byte    `json:"sealed,omitempty"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

// PracticeLogInput defines model for PracticeLogInput.
type PracticeLogInput struct {
	Deleted    *bool `json:"deleted,omitempty"`
	KeyVersion int   `json:"keyVersion"`

	// Sealed nonce ‖ ciphertext ‖ tag over the padded session JSON (a multiple of 256
	// bytes, at most 16 KiB). Omitted, together with deleted: true, for a deletion.
	Sealed *[]byte `json:"sealed,omitempty"`

	// UpdatedAt The client's clock; the newer write wins
	UpdatedAt time.Time `json:"updatedAt"`
}

// RecoveryBox defines model for RecoveryBox.
type RecoveryBox struct {
	Box       []byte    `json:"box"`
	Kind      int       `json:"kind"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// RecoveryBoxInput defines model for RecoveryBoxInput.
type RecoveryBoxInput struct {
	// Box 60 bytes
	Box []byte `json:"box"`
}

// RecoveryBoxList defines model for RecoveryBoxList.
type RecoveryBoxList struct {
	Boxes []RecoveryBox `json:"boxes"`
}

// RotationWrap defines model for RotationWrap.
type RotationWrap struct {
	// AuthType signature: Ed25519 by the identity key; enrol: HMAC from the QR secret; self:
	// HMAC from the device's own ECDH (docs/crypto.md, Wraps).
	AuthType AuthType `json:"authType"`

	// Authenticator 64 bytes for a signature, 32 for a tag
	Authenticator []byte `json:"authenticator"`

	// Box nonce ‖ ciphertext ‖ tag, 60 bytes
	Box      []byte `json:"box"`
	DeviceId UUID   `json:"deviceId"`

	// EphemeralKey 65 bytes
	EphemeralKey []byte `json:"ephemeralKey"`
	KeyVersion   int    `json:"keyVersion"`
	Kind         int    `json:"kind"`
}

// SignedStatement Exact payload bytes (compact JSON, sorted keys) and their Ed25519 signature.
type SignedStatement struct {
	Payload   []byte `json:"payload"`
	Signature []byte `json:"signature"`
}

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	// Cursor <generation>:<xid>; pass back as since
	Cursor string        `json:"cursor"`
	Full   bool          `json:"full"`
	Logs   []PracticeLog `json:"logs"`
}

// Tier defines model for Tier.
type Tier string

// UUID defines model for UUID.
type UUID = uuid.UUID

// Version defines model for Version.
type Version struct {
	Go       string `json:"go"`
	Modified bool   `json:"modified"`
	Revision string `json:"revision"`

	// Short 7 characters, with -dirty for a modified tree
	Short string  `json:"short"`
	Time  *string `json:"time,omitempty"`
}

// Wrap defines model for Wrap.
type Wrap struct {
	// AuthType signature: Ed25519 by the identity key; enrol: HMAC from the QR secret; self:
	// HMAC from the device's own ECDH (docs/crypto.md, Wraps).
	AuthType AuthType `json:"authType"`

	// Authenticator 64 bytes for a signature, 32 for a tag
	Authenticator []byte `json:"authenticator"`

	// Box nonce ‖ ciphertext ‖ tag, 60 bytes
	Box       []byte    `json:"box"`
	CreatedAt time.Time `json:"createdAt"`
	DeviceId  UUID      `json:"deviceId"`

	// EphemeralKey 65 bytes
	EphemeralKey []byte `json:"ephemeralKey"`
	KeyVersion   int    `json:"keyVersion"`
	Kind         int    `json:"kind"`
}

// WrapInput defines model for WrapInput.
type WrapInput struct {
	// AuthType signature: Ed25519 by the identity key; enrol: HMAC from the QR secret; self:
	// HMAC from the device's own ECDH (docs/crypto.md, Wraps).
	AuthType AuthType `json:"authType"`

	// Authenticator 64 bytes for a signature, 32 for a tag
	Authenticator []byte `json:"authenticator"`

	// Box nonce ‖ ciphertext ‖ tag, 60 bytes
	Box []byte `json:"box"`

	// EphemeralKey 65 bytes
	EphemeralKey []byte `json:"ephemeralKey"`
	KeyVersion   int    `json:"keyVersion"`
	Kind         int    `json:"kind"`
}

// WrapList defines model for WrapList.
type WrapList struct {
	Wraps []Wrap `json:"wraps"`
}

// Authorization defines model for Authorization.
type Authorization = string

// DeviceId defines model for DeviceId.
type DeviceId = UUID

// Kind defines model for Kind.
type Kind = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListDevicesParams defines parameters for ListDevices.
type ListDevicesParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// RegisterDeviceParams defines parameters for RegisterDevice.
type RegisterDeviceParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// DeleteDeviceParams defines parameters for DeleteDevice.
type DeleteDeviceParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// ListWrapsParams defines parameters for ListWraps.
type ListWrapsParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// PutWrapParams defines parameters for PutWrap.
type PutWrapParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// GetMeParams defines parameters for GetMe.
type GetMeParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// GetDeviceListParams defines parameters for GetDeviceList.
type GetDeviceListParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// PutDeviceListParams defines parameters for PutDeviceList.
type PutDeviceListParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// PutIdentityParams defines parameters for PutIdentity.
type PutIdentityParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// RotatePracticeKeyParams defines parameters for RotatePracticeKey.
type RotatePracticeKeyParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// ListRecoveryBoxesParams defines parameters for ListRecoveryBoxes.
type ListRecoveryBoxesParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// PutRecoveryBoxParams defines parameters for PutRecoveryBox.
type PutRecoveryBoxParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// SignOutParams defines parameters for SignOut.
type SignOutParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// PutPracticeLogParams defines parameters for PutPracticeLog.
type PutPracticeLogParams struct {
	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// SyncParams defines parameters for Sync.
type SyncParams struct {
	Since *string `form:"since,omitempty" json:"since,omitempty"`

	// Authorization Bearer <session token>
	Authorization Authorization `json:"Authorization"`
}

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceInput

// PutWrapJSONRequestBody defines body for PutWrap for application/json ContentType.
type PutWrapJSONRequestBody = WrapInput

// PutDeviceListJSONRequestBody defines body for PutDeviceList for application/json ContentType.
type PutDeviceListJSONRequestBody = SignedStatement

// PutIdentityJSONRequestBody defines body for PutIdentity for application/json ContentType.
type PutIdentityJSONRequestBody = IdentityKey

// RotatePracticeKeyJSONRequestBody defines body for RotatePracticeKey for application/json ContentType.
type RotatePracticeKeyJSONRequestBody = KeyRotation

// PutRecoveryBoxJSONRequestBody defines body for PutRecoveryBox for application/json ContentType.
type PutRecoveryBoxJSONRequestBody = RecoveryBoxInput

// PutPracticeLogJSONRequestBody defines body for PutPracticeLog for application/json ContentType.
type PutPracticeLogJSONRequestBody = PracticeLogInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/devices)
	ListDevices(ctx *echo.Context, params ListDevicesParams) error

	// (POST /api/devices)
	RegisterDevice(ctx *echo.Context, params RegisterDeviceParams) error

	// (DELETE /api/devices/{deviceId})
	DeleteDevice(ctx *echo.Context, deviceId DeviceId, params DeleteDeviceParams) error

	// (GET /api/devices/{deviceId}/wraps)
	ListWraps(ctx *echo.Context, deviceId DeviceId, params ListWrapsParams) error

	// (POST /api/devices/{deviceId}/wraps)
	PutWrap(ctx *echo.Context, deviceId DeviceId, params PutWrapParams) error

	// (GET /api/me)
	GetMe(ctx *echo.Context, params GetMeParams) error

	// (GET /api/me/device-list)
	GetDeviceList(ctx *echo.Context, params GetDeviceListParams) error

	// (PUT /api/me/device-list)
	PutDeviceList(ctx *echo.Context, params PutDeviceListParams) error

	// (PUT /api/me/identity)
	PutIdentity(ctx *echo.Context, params PutIdentityParams) error

	// (POST /api/me/key-rotations)
	RotatePracticeKey(ctx *echo.Context, params RotatePracticeKeyParams) error

	// (GET /api/me/recovery-boxes)
	ListRecoveryBoxes(ctx *echo.Context, params ListRecoveryBoxesParams) error

	// (PUT /api/me/recovery-boxes/{kind})
	PutRecoveryBox(ctx *echo.Context, kind Kind, params PutRecoveryBoxParams) error

	// (DELETE /api/me/session)
	SignOut(ctx *echo.Context, params SignOutParams) error

	// (PUT /api/practice-logs/{logId})
	PutPracticeLog(ctx *echo.Context, logId UUID, params PutPracticeLogParams) error

	// (GET /api/sync)
	Sync(ctx *echo.Context, params SyncParams) error

	// (GET /api/version)
	GetVersion(ctx *echo.Context) error

	// (GET /healthz)
	GetHealth(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListDevices converts echo context to params.
func (w *ServerInterfaceWrapper) ListDevices(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDevicesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListDevices(ctx, params)
	return err
}

// RegisterDevice converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterDevice(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterDeviceParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterDevice(ctx, params)
	return err
}

// DeleteDevice converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDevice(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "deviceId" -------------
	var deviceId DeviceId

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", ctx.Param("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deviceId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteDeviceParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDevice(ctx, deviceId, params)
	return err
}

// ListWraps converts echo context to params.
func (w *ServerInterfaceWrapper) ListWraps(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "deviceId" -------------
	var deviceId DeviceId

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", ctx.Param("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deviceId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWrapsParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListWraps(ctx, deviceId, params)
	return err
}

// PutWrap converts echo context to params.
func (w *ServerInterfaceWrapper) PutWrap(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "deviceId" -------------
	var deviceId DeviceId

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", ctx.Param("deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deviceId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutWrapParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutWrap(ctx, deviceId, params)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMeParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx, params)
	return err
}

// GetDeviceList converts echo context to params.
func (w *ServerInterfaceWrapper) GetDeviceList(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeviceListParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDeviceList(ctx, params)
	return err
}

// PutDeviceList converts echo context to params.
func (w *ServerInterfaceWrapper) PutDeviceList(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PutDeviceListParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutDeviceList(ctx, params)
	return err
}

// PutIdentity converts echo context to params.
func (w *ServerInterfaceWrapper) PutIdentity(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PutIdentityParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutIdentity(ctx, params)
	return err
}

// RotatePracticeKey converts echo context to params.
func (w *ServerInterfaceWrapper) RotatePracticeKey(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RotatePracticeKeyParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RotatePracticeKey(ctx, params)
	return err
}

// ListRecoveryBoxes converts echo context to params.
func (w *ServerInterfaceWrapper) ListRecoveryBoxes(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecoveryBoxesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRecoveryBoxes(ctx, params)
	return err
}

// PutRecoveryBox converts echo context to params.
func (w *ServerInterfaceWrapper) PutRecoveryBox(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "kind" -------------
	var kind Kind

	err = runtime.BindStyledParameterWithOptions("simple", "kind", ctx.Param("kind"), &kind, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter kind: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutRecoveryBoxParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutRecoveryBox(ctx, kind, params)
	return err
}

// SignOut converts echo context to params.
func (w *ServerInterfaceWrapper) SignOut(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SignOutParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignOut(ctx, params)
	return err
}

// PutPracticeLog converts echo context to params.
func (w *ServerInterfaceWrapper) PutPracticeLog(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "logId" -------------
	var logId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "logId", ctx.Param("logId"), &logId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter logId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutPracticeLogParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutPracticeLog(ctx, logId, params)
	return err
}

// Sync converts echo context to params.
func (w *ServerInterfaceWrapper) Sync(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SyncParams
	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", ctx.QueryParams(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter since: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Authorization, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Authorization: %s", err))
		}

		params.Authorization = Authorization
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Authorization is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Sync(ctx, params)
	return err
}

// GetVersion converts echo context to params.
func (w *ServerInterfaceWrapper) GetVersion(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVersion(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth, options.OperationMiddlewares["getHealth"]...)
	router.GET(options.BaseURL+"/api/version", wrapper.GetVersion, options.OperationMiddlewares["getVersion"]...)
	router.GET(options.BaseURL+"/api/me", wrapper.GetMe, options.OperationMiddlewares["getMe"]...)
	router.DELETE(options.BaseURL+"/api/me/session", wrapper.SignOut, options.OperationMiddlewares["signOut"]...)
	router.PUT(options.BaseURL+"/api/me/identity", wrapper.PutIdentity, options.OperationMiddlewares["putIdentity"]...)
	router.GET(options.BaseURL+"/api/me/device-list", wrapper.GetDeviceList, options.OperationMiddlewares["getDeviceList"]...)
	router.PUT(options.BaseURL+"/api/me/device-list", wrapper.PutDeviceList, options.OperationMiddlewares["putDeviceList"]...)
	router.POST(options.BaseURL+"/api/me/key-rotations", wrapper.RotatePracticeKey, options.OperationMiddlewares["rotatePracticeKey"]...)
	router.GET(options.BaseURL+"/api/me/recovery-boxes", wrapper.ListRecoveryBoxes, options.OperationMiddlewares["listRecoveryBoxes"]...)
	router.PUT(options.BaseURL+"/api/me/recovery-boxes/:kind", wrapper.PutRecoveryBox, options.OperationMiddlewares["putRecoveryBox"]...)
	router.GET(options.BaseURL+"/api/devices", wrapper.ListDevices, options.OperationMiddlewares["listDevices"]...)
	router.POST(options.BaseURL+"/api/devices", wrapper.RegisterDevice, options.OperationMiddlewares["registerDevice"]...)
	router.DELETE(options.BaseURL+"/api/devices/:deviceId", wrapper.DeleteDevice, options.OperationMiddlewares["deleteDevice"]...)
	router.GET(options.BaseURL+"/api/devices/:deviceId/wraps", wrapper.ListWraps, options.OperationMiddlewares["listWraps"]...)
	router.POST(options.BaseURL+"/api/devices/:deviceId/wraps", wrapper.PutWrap, options.OperationMiddlewares["putWrap"]...)
	router.PUT(options.BaseURL+"/api/practice-logs/:logId", wrapper.PutPracticeLog, options.OperationMiddlewares["putPracticeLog"]...)
	router.GET(options.BaseURL+"/api/sync", wrapper.Sync, options.OperationMiddlewares["sync"]...)

}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedResponse struct {
}

type ListDevicesRequestObject struct {
	Params ListDevicesParams
}

type ListDevicesResponseObject interface {
	VisitListDevicesResponse(w http.ResponseWriter) error
}

type ListDevices200JSONResponse DeviceList

func (response ListDevices200JSONResponse) VisitListDevicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDevices401Response = UnauthorizedResponse

func (response ListDevices401Response) VisitListDevicesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type RegisterDeviceRequestObject struct {
	Params RegisterDeviceParams
	Body   *RegisterDeviceJSONRequestBody
}

type RegisterDeviceResponseObject interface {
	VisitRegisterDeviceResponse(w http.ResponseWriter) error
}

type RegisterDevice200JSONResponse Device

func (response RegisterDevice200JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice201JSONResponse Device

func (response RegisterDevice201JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterDevice400JSONResponse) VisitRegisterDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterDevice401Response = UnauthorizedResponse

func (response RegisterDevice401Response) VisitRegisterDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteDeviceRequestObject struct {
	DeviceId DeviceId `json:"deviceId"`
	Params   DeleteDeviceParams
}

type DeleteDeviceResponseObject interface {
	VisitDeleteDeviceResponse(w http.ResponseWriter) error
}

type DeleteDevice204Response struct {
}

func (response DeleteDevice204Response) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDevice401Response = UnauthorizedResponse

func (response DeleteDevice401Response) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type DeleteDevice404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteDevice404JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListWrapsRequestObject struct {
	DeviceId DeviceId `json:"deviceId"`
	Params   ListWrapsParams
}

type ListWrapsResponseObject interface {
	VisitListWrapsResponse(w http.ResponseWriter) error
}

type ListWraps200JSONResponse WrapList

func (response ListWraps200JSONResponse) VisitListWrapsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListWraps401Response = UnauthorizedResponse

func (response ListWraps401Response) VisitListWrapsResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type ListWraps404JSONResponse struct{ NotFoundJSONResponse }

func (response ListWraps404JSONResponse) VisitListWrapsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutWrapRequestObject struct {
	DeviceId DeviceId `json:"deviceId"`
	Params   PutWrapParams
	Body     *PutWrapJSONRequestBody
}

type PutWrapResponseObject interface {
	VisitPutWrapResponse(w http.ResponseWriter) error
}

type PutWrap204Response struct {
}

func (response PutWrap204Response) VisitPutWrapResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutWrap400JSONResponse struct{ BadRequestJSONResponse }

func (response PutWrap400JSONResponse) VisitPutWrapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutWrap401Response = UnauthorizedResponse

func (response PutWrap401Response) VisitPutWrapResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PutWrap404JSONResponse struct{ NotFoundJSONResponse }

func (response PutWrap404JSONResponse) VisitPutWrapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
	Params GetMeParams
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401Response = UnauthorizedResponse

func (response GetMe401Response) VisitGetMeResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetDeviceListRequestObject struct {
	Params GetDeviceListParams
}

type GetDeviceListResponseObject interface {
	VisitGetDeviceListResponse(w http.ResponseWriter) error
}

type GetDeviceList200JSONResponse SignedStatement

func (response GetDeviceList200JSONResponse) VisitGetDeviceListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDeviceList401Response = UnauthorizedResponse

func (response GetDeviceList401Response) VisitGetDeviceListResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetDeviceList404JSONResponse struct{ NotFoundJSONResponse }

func (response GetDeviceList404JSONResponse) VisitGetDeviceListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutDeviceListRequestObject struct {
	Params PutDeviceListParams
	Body   *PutDeviceListJSONRequestBody
}

type PutDeviceListResponseObject interface {
	VisitPutDeviceListResponse(w http.ResponseWriter) error
}

type PutDeviceList204Response struct {
}

func (response PutDeviceList204Response) VisitPutDeviceListResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutDeviceList400JSONResponse struct{ BadRequestJSONResponse }

func (response PutDeviceList400JSONResponse) VisitPutDeviceListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutDeviceList401Response = UnauthorizedResponse

func (response PutDeviceList401Response) VisitPutDeviceListResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PutDeviceList409JSONResponse struct{ ConflictJSONResponse }

func (response PutDeviceList409JSONResponse) VisitPutDeviceListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type PutIdentityRequestObject struct {
	Params PutIdentityParams
	Body   *PutIdentityJSONRequestBody
}

type PutIdentityResponseObject interface {
	VisitPutIdentityResponse(w http.ResponseWriter) error
}

type PutIdentity204Response struct {
}

func (response PutIdentity204Response) VisitPutIdentityResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutIdentity400JSONResponse struct{ BadRequestJSONResponse }

func (response PutIdentity400JSONResponse) VisitPutIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutIdentity401Response = UnauthorizedResponse

func (response PutIdentity401Response) VisitPutIdentityResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PutIdentity409JSONResponse struct{ ConflictJSONResponse }

func (response PutIdentity409JSONResponse) VisitPutIdentityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RotatePracticeKeyRequestObject struct {
	Params RotatePracticeKeyParams
	Body   *RotatePracticeKeyJSONRequestBody
}

type RotatePracticeKeyResponseObject interface {
	VisitRotatePracticeKeyResponse(w http.ResponseWriter) error
}

type RotatePracticeKey204Response struct {
}

func (response RotatePracticeKey204Response) VisitRotatePracticeKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RotatePracticeKey400JSONResponse struct{ BadRequestJSONResponse }

func (response RotatePracticeKey400JSONResponse) VisitRotatePracticeKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RotatePracticeKey401Response = UnauthorizedResponse

func (response RotatePracticeKey401Response) VisitRotatePracticeKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type RotatePracticeKey409JSONResponse struct{ ConflictJSONResponse }

func (response RotatePracticeKey409JSONResponse) VisitRotatePracticeKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListRecoveryBoxesRequestObject struct {
	Params ListRecoveryBoxesParams
}

type ListRecoveryBoxesResponseObject interface {
	VisitListRecoveryBoxesResponse(w http.ResponseWriter) error
}

type ListRecoveryBoxes200JSONResponse RecoveryBoxList

func (response ListRecoveryBoxes200JSONResponse) VisitListRecoveryBoxesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRecoveryBoxes401Response = UnauthorizedResponse

func (response ListRecoveryBoxes401Response) VisitListRecoveryBoxesResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PutRecoveryBoxRequestObject struct {
	Kind   Kind `json:"kind"`
	Params PutRecoveryBoxParams
	Body   *PutRecoveryBoxJSONRequestBody
}

type PutRecoveryBoxResponseObject interface {
	VisitPutRecoveryBoxResponse(w http.ResponseWriter) error
}

type PutRecoveryBox204Response struct {
}

func (response PutRecoveryBox204Response) VisitPutRecoveryBoxResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutRecoveryBox400JSONResponse struct{ BadRequestJSONResponse }

func (response PutRecoveryBox400JSONResponse) VisitPutRecoveryBoxResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutRecoveryBox401Response = UnauthorizedResponse

func (response PutRecoveryBox401Response) VisitPutRecoveryBoxResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SignOutRequestObject struct {
	Params SignOutParams
}

type SignOutResponseObject interface {
	VisitSignOutResponse(w http.ResponseWriter) error
}

type SignOut204Response struct {
}

func (response SignOut204Response) VisitSignOutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SignOut401Response = UnauthorizedResponse

func (response SignOut401Response) VisitSignOutResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PutPracticeLogRequestObject struct {
	LogId  UUID `json:"logId"`
	Params PutPracticeLogParams
	Body   *PutPracticeLogJSONRequestBody
}

type PutPracticeLogResponseObject interface {
	VisitPutPracticeLogResponse(w http.ResponseWriter) error
}

type PutPracticeLog200JSONResponse PracticeLog

func (response PutPracticeLog200JSONResponse) VisitPutPracticeLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutPracticeLog400JSONResponse struct{ BadRequestJSONResponse }

func (response PutPracticeLog400JSONResponse) VisitPutPracticeLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutPracticeLog401Response = UnauthorizedResponse

func (response PutPracticeLog401Response) VisitPutPracticeLogResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PutPracticeLog404JSONResponse struct{ NotFoundJSONResponse }

func (response PutPracticeLog404JSONResponse) VisitPutPracticeLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutPracticeLog422JSONResponse OldKeyError

func (response PutPracticeLog422JSONResponse) VisitPutPracticeLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SyncRequestObject struct {
	Params SyncParams
}

type SyncResponseObject interface {
	VisitSyncResponse(w http.ResponseWriter) error
}

type Sync200JSONResponse SyncResponse

func (response Sync200JSONResponse) VisitSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Sync400JSONResponse struct{ BadRequestJSONResponse }

func (response Sync400JSONResponse) VisitSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Sync401Response = UnauthorizedResponse

func (response Sync401Response) VisitSyncResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse Version

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200TextResponse string

func (response GetHealth200TextResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/devices)
	ListDevices(ctx context.Context, request ListDevicesRequestObject) (ListDevicesResponseObject, error)

	// (POST /api/devices)
	RegisterDevice(ctx context.Context, request RegisterDeviceRequestObject) (RegisterDeviceResponseObject, error)

	// (DELETE /api/devices/{deviceId})
	DeleteDevice(ctx context.Context, request DeleteDeviceRequestObject) (DeleteDeviceResponseObject, error)

	// (GET /api/devices/{deviceId}/wraps)
	ListWraps(ctx context.Context, request ListWrapsRequestObject) (ListWrapsResponseObject, error)

	// (POST /api/devices/{deviceId}/wraps)
	PutWrap(ctx context.Context, request PutWrapRequestObject) (PutWrapResponseObject, error)

	// (GET /api/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)

	// (GET /api/me/device-list)
	GetDeviceList(ctx context.Context, request GetDeviceListRequestObject) (GetDeviceListResponseObject, error)

	// (PUT /api/me/device-list)
	PutDeviceList(ctx context.Context, request PutDeviceListRequestObject) (PutDeviceListResponseObject, error)

	// (PUT /api/me/identity)
	PutIdentity(ctx context.Context, request PutIdentityRequestObject) (PutIdentityResponseObject, error)

	// (POST /api/me/key-rotations)
	RotatePracticeKey(ctx context.Context, request RotatePracticeKeyRequestObject) (RotatePracticeKeyResponseObject, error)

	// (GET /api/me/recovery-boxes)
	ListRecoveryBoxes(ctx context.Context, request ListRecoveryBoxesRequestObject) (ListRecoveryBoxesResponseObject, error)

	// (PUT /api/me/recovery-boxes/{kind})
	PutRecoveryBox(ctx context.Context, request PutRecoveryBoxRequestObject) (PutRecoveryBoxResponseObject, error)

	// (DELETE /api/me/session)
	SignOut(ctx context.Context, request SignOutRequestObject) (SignOutResponseObject, error)

	// (PUT /api/practice-logs/{logId})
	PutPracticeLog(ctx context.Context, request PutPracticeLogRequestObject) (PutPracticeLogResponseObject, error)

	// (GET /api/sync)
	Sync(ctx context.Context, request SyncRequestObject) (SyncResponseObject, error)

	// (GET /api/version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)

	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListDevices operation middleware
func (sh *strictHandler) ListDevices(ctx *echo.Context, params ListDevicesParams) error {
	var request ListDevicesRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListDevices(ctx.Request().Context(), request.(ListDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDevices")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListDevicesResponseObject); ok {
		return validResponse.VisitListDevicesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterDevice operation middleware
func (sh *strictHandler) RegisterDevice(ctx *echo.Context, params RegisterDeviceParams) error {
	var request RegisterDeviceRequestObject

	request.Params = params

	var body RegisterDeviceJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterDevice(ctx.Request().Context(), request.(RegisterDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterDevice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterDeviceResponseObject); ok {
		return validResponse.VisitRegisterDeviceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteDevice operation middleware
func (sh *strictHandler) DeleteDevice(ctx *echo.Context, deviceId DeviceId, params DeleteDeviceParams) error {
	var request DeleteDeviceRequestObject

	request.DeviceId = deviceId
	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDevice(ctx.Request().Context(), request.(DeleteDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDevice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteDeviceResponseObject); ok {
		return validResponse.VisitDeleteDeviceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListWraps operation middleware
func (sh *strictHandler) ListWraps(ctx *echo.Context, deviceId DeviceId, params ListWrapsParams) error {
	var request ListWrapsRequestObject

	request.DeviceId = deviceId
	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListWraps(ctx.Request().Context(), request.(ListWrapsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWraps")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListWrapsResponseObject); ok {
		return validResponse.VisitListWrapsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutWrap operation middleware
func (sh *strictHandler) PutWrap(ctx *echo.Context, deviceId DeviceId, params PutWrapParams) error {
	var request PutWrapRequestObject

	request.DeviceId = deviceId
	request.Params = params

	var body PutWrapJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutWrap(ctx.Request().Context(), request.(PutWrapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutWrap")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutWrapResponseObject); ok {
		return validResponse.VisitPutWrapResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *echo.Context, params GetMeParams) error {
	var request GetMeRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetDeviceList operation middleware
func (sh *strictHandler) GetDeviceList(ctx *echo.Context, params GetDeviceListParams) error {
	var request GetDeviceListRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceList(ctx.Request().Context(), request.(GetDeviceListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDeviceListResponseObject); ok {
		return validResponse.VisitGetDeviceListResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutDeviceList operation middleware
func (sh *strictHandler) PutDeviceList(ctx *echo.Context, params PutDeviceListParams) error {
	var request PutDeviceListRequestObject

	request.Params = params

	var body PutDeviceListJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutDeviceList(ctx.Request().Context(), request.(PutDeviceListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDeviceList")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutDeviceListResponseObject); ok {
		return validResponse.VisitPutDeviceListResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutIdentity operation middleware
func (sh *strictHandler) PutIdentity(ctx *echo.Context, params PutIdentityParams) error {
	var request PutIdentityRequestObject

	request.Params = params

	var body PutIdentityJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutIdentity(ctx.Request().Context(), request.(PutIdentityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutIdentity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutIdentityResponseObject); ok {
		return validResponse.VisitPutIdentityResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RotatePracticeKey operation middleware
func (sh *strictHandler) RotatePracticeKey(ctx *echo.Context, params RotatePracticeKeyParams) error {
	var request RotatePracticeKeyRequestObject

	request.Params = params

	var body RotatePracticeKeyJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RotatePracticeKey(ctx.Request().Context(), request.(RotatePracticeKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RotatePracticeKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RotatePracticeKeyResponseObject); ok {
		return validResponse.VisitRotatePracticeKeyResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListRecoveryBoxes operation middleware
func (sh *strictHandler) ListRecoveryBoxes(ctx *echo.Context, params ListRecoveryBoxesParams) error {
	var request ListRecoveryBoxesRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRecoveryBoxes(ctx.Request().Context(), request.(ListRecoveryBoxesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRecoveryBoxes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListRecoveryBoxesResponseObject); ok {
		return validResponse.VisitListRecoveryBoxesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutRecoveryBox operation middleware
func (sh *strictHandler) PutRecoveryBox(ctx *echo.Context, kind Kind, params PutRecoveryBoxParams) error {
	var request PutRecoveryBoxRequestObject

	request.Kind = kind
	request.Params = params

	var body PutRecoveryBoxJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutRecoveryBox(ctx.Request().Context(), request.(PutRecoveryBoxRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutRecoveryBox")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutRecoveryBoxResponseObject); ok {
		return validResponse.VisitPutRecoveryBoxResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SignOut operation middleware
func (sh *strictHandler) SignOut(ctx *echo.Context, params SignOutParams) error {
	var request SignOutRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SignOut(ctx.Request().Context(), request.(SignOutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SignOut")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignOutResponseObject); ok {
		return validResponse.VisitSignOutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutPracticeLog operation middleware
func (sh *strictHandler) PutPracticeLog(ctx *echo.Context, logId UUID, params PutPracticeLogParams) error {
	var request PutPracticeLogRequestObject

	request.LogId = logId
	request.Params = params

	var body PutPracticeLogJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutPracticeLog(ctx.Request().Context(), request.(PutPracticeLogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutPracticeLog")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutPracticeLogResponseObject); ok {
		return validResponse.VisitPutPracticeLogResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Sync operation middleware
func (sh *strictHandler) Sync(ctx *echo.Context, params SyncParams) error {
	var request SyncRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Sync(ctx.Request().Context(), request.(SyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Sync")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SyncResponseObject); ok {
		return validResponse.VisitSyncResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(ctx *echo.Context) error {
	var request GetVersionRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx.Request().Context(), request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		return validResponse.VisitGetVersionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fvdcts4sn6VLp5TFbsOLdmOk1Mj11w4cc6MT343zsxejFJliGhRGJEABwDlaFKu2qfYR9kX2DfZJ9lq",
	"AKRIibTsxPZkam8SiwKBbvTf1z/6HCUqL5REaU00+hwVTLMcLWr36aS0M6XF78wKJekBR5NoUfiP0TNk",
	"GjWMy/39x4lBY4SSYNUcpXuEURwJWjdDxlFHcSRZjtFobds40vhbKTTyaGR1iXFkkhnmjM6zy4JeMFYL",
	"mUZXV3F0iguR4Bmnb93mBbOz1da8+vq6Xf9b4zQaRf81XPE+9N+a4U8/nZ26g14KyTdZPoDvodAssSJB",
	"mOMyhkP4HgRHaYVdgkHkgyjuomwu5PVU5eyTyMs8Gh3GUS6k//sgru5ASIsp6uiKiNNoCiUNOik9Y/w9",
	"/laisfQpUdKidH+yoshE4m55+KvxErzZLbzQWoWj2vx/mCFofxgIAznLpkrnyEFpmDKRGViwTHB35iC6",
	"iqPnSk4zkTwAadVJBi6FnYGdIRirNHIwlll01LxR9v9UKfn9U/NGgSmTGWg0qtQJwlRpsDNhgCWJKqV1",
	"9PwkWbAF7FC218IYIdMYSjmX6lLSJWtcqDnx1DS3gdPYQFNluB+c3qzvaUQqmS01juAFP3zy5OA7mCzd",
	"ZdVKPMflMaDUKhvBj69PnsNUq9wt+ct7MJhotMdgMJuOxrL9vbe+RwaI2BfPT3+EHa4SM0z0srBqkPMY",
	"/qpZYXYHY7J7lKTiv6xocs+0yqI4ov2jj/G6B6gcgPNVWhWorfBWkGhkFvmJEygpJbPkD5jFPStyjDq2",
	"Evxm3iCOinKSieQlLlubT5a2c18rUG/b+YNwttx0CL8QQc2zwk5xg7fVjajJr5jY1Y2cyaK0m9fSoryt",
	"Ck+f7BEHUEqiT6MxyKFQQlogxZohpJm6FAhJqRfE6P0xvsFzP5+vhOlg02ue+1NYzM02Kvxe0VV9DNOa",
	"LTfoqrbtIseb/gYlWD3ejF3Nnf2yrn3Pgh0GmV0jzseHQJIw0UiWWbbugYJ5b5dbryy6qHuJy/fK1oCg",
	"TZ3Ey59Rm/BdHcQON4NYHF2SI7ixvKozyX1slVqDjOqcLlZe4/3p0W2cS+V4392DbONojsuGTNZCZqk1",
	"SgsLvwDU1Jl9E+BEHQCkw2k1TomvtZq3GX+Jyx7bSTw9L1skb6rOrUws7ti1i7B3gelXKu1SiwzvLbjM",
	"t7BrkGXIWyf3Cbss+O2C4FZZrnbccmk98SfcXIOziVIZMrnJ+XWgt3kLbR2WSiYI//rb3yERxQy1xU/W",
	"fbQsBbVA7VWacd5ATf9//vYN7DDIy8yKIkPS/MMnT8fS2VwMzEKujIWDp/BSPNsdwNtcWIs8BqtStDPU",
	"HmQG7kbgwLzDeMw/JPzrQM7tZLaJtpNMoLSPDCSZSubHjhuJl0SBFhbhUkjTPObmwr6FnN9jQle5fKY+",
	"bYp44h9u90Qho9qU7deqbcitiJBbcNKjsYGdNay0H9zxbaMp7baFjm5EM1GfbhGHmgLaFh79zp1ENaMs",
	"5UVZ9nYajX65/mxa7e/yKu6Op2f8xmn3Jvo64x20fryKo3ORSuTnllnMQyK3FiU/scRCwZaZYtzLD3bo",
	"cHpMLiAGo7RFToHO7AKTnMxL6Do1qjMTSurXkJjf9kaaX29zg9XraCwc09ykS3TnS5m8D1WBzsBqlN68",
	"IV+6SVGidoJ3n3HkH38S3H8+hoIZAxOWzIEZMEImnWxOyyzrdvSZSm+uy81IvE2XA2Ph7HBQ1/18CKlJ",
	"lXPOmOaXzKWcFulfo6bWPehKOp16NmVXli5UthfG0ae9VO2Fh7Rk4F5sPN8TeaG0N3dmZ9VOxFYjEraF",
	"l6oOrBNHueJiKvpCq8aFWIMUq1fNLNDQ1ob/hWTG6PJRm9gHuD0utF2GwFadCFZjT/6X43ZcVpNWEdLg",
	"JSZuu+R3dy7pCwoFd+PFrs/jPwYme6ISa1R0riOhrvxcxe4dlJYqW13G//Qo+EQv3dq/xPD4MDyzLL0J",
	"hOkMmdcBsxhuHlDjCIsZ5qhZ1lPGuPlOtwGcFVy5cV22E5O0QFaLkQqv1JJdF1ifGXTjhdvl0zfKo/tS",
	"Z1on5FR1A1aDmlC3q70a8LAdJpmamBh8bcGFWxdtjQvhYKoYbgZwZkHiAvVYakxQLNAAW2WkrnQaAwNN",
	"ZVxwSurK8LSbsJDMMJkbUDJbghG/E5b3RayxdFUs2Hlzdv4B3u0dPnm664tdnpKNiG9WyQM6HOFtRVio",
	"6BrLterm7gCeCcn0EqYCM26AaSTeJGeaw4QZfHoEOxdeS0duwwsqhY7lcyUtsQhToY0dAXJhfbV4KjKM",
	"iQoJFzmbI6QoLwZAF30iuVaChwyByvEhkCMfS1eTpU2UcicQWNoTku7NwSCK6CSGGOgbENL7+5OioPN+",
	"UCql/3OWigQyIecreASnL34ey0kpMv7IwLu35x9gyAox5LgYVvkVMa4xFcaiRg6qtEZwbHLEDJ35XHE8",
	"nzGNPleywmYYjaLTUsn0n/8g/uDk3VkUR4vKaqMDUltVoGSFiEbR48H+4HEUu2jqtL6ipSrjpOiMRRUB",
	"4pAXj8iETsOauNX06gksqyXDdvfq6uNaN+Zwf//OuguNimdnL2bVTXhkQvHduL7C0f5B3941scNW88Ht",
	"XyjTAQveB0EaYOEQ3yKoBCxk6rstLHffAEsZaRraUksTLEgYS+v8+4Sm2wKpzvAc34lMXJPqmeLLOxZH",
	"wBVtZ2l1iVf3rgldWnCSaWR82TA3pwGH+wcPcPj79qFH+/t9e63UrtGu/FJNvYpbZj78XGGsq1XJqUuP",
	"c0XhREn0lc4u8wmBxIALfpuKeuo2vxs1jbe+UHe7O9zMUR+H/EtdAL10tP2luol6rSSGNSDp9cCuF/jH",
	"XuLdWWiNzDrM5Nw1Tb1OFZQ/Ka99lTd8MHH1ufhzD9aYo5DIu9ZGYtBYZCwhh14vrPy/kHwsyYhCyB7A",
	"yQpUQQvhEmRZoPY5pQsaxm60oseyxmGOuAqFnJycgl3BTY0OkZhj37K2LPXwywFC5C6fIUDogUZbF9+V",
	"ThUfXBPvPkI18t6bxKejHk14SG/+FU4nx1738gPa1/gtQ7vX2Dde43MiwurNSZGvipM5Bge9l4Xcse/S",
	"GojzG7689cpvz01Sm8TYKskM0JVu4GE9btnhcF2v18ycz5V42UEj7FDWDRcNwV3s+sSvqmjnpbEgWY5j",
	"6Rx1aVDH/mWXAFeQppGJWUVJYTUgJfR6Rj6WVrjqX8K0XgKrW8NsohbYHKpSEn3WPalUtmuQqMfd3rGa",
	"3b0j7dSwP4s7/W77S/VYXttLVKLzoyZdQAGtz+hWoKCqnNRiX6lUDEomOIBztHY9SxxLnyYKZwJqTxXH",
	"lF+K6RTdTAIlkoJ0d1oaary6rgNMtUDJDczYAqEQktRO2B4tqyZpvlEdaw76/Ifo1xyXezo0GR1T3XD0",
	"tcvT1kdRyHmtyqnwP3Dg3aFLNLwz9F4rtMjDO2Pp6nfZsjGiSJszCzOVeTAZRkRASRzAK5XWdctS8gA+",
	"VcbHsvaGGn1NLqin96hHh4dQSiuy1kkaaS96lHfpqeu5YtXz8oXhb1Fbm4NfX6qtntc/j7rq0FXfq5vx",
	"ATdtYo2WoroaQnMmfFOdqq0hUbyjHkahsdHT/7bLlOuzDF0ZsAcN7h7vBM+2RTP8THnnVSNsbQSDBpH3",
	"n+i5Hw/clyVujLD8aYJHS4KhV3Bdxe4FhXoHbcPiY1eaczPvYKwqDFwqPRcy3bQgQnBvy3tIY7ou0uNf",
	"Vd5BrlY5kj0aZRh+zlR61lLsnsJNcDDhnmJQ2l1VNYsWg5gS8hcmDI/tBLBejZeNZT03tUvBUa5h/WNA",
	"4efemH+RSUP7CNNcqNVlDxZrDnV8vfl1/L7GXdTX/uznnix2Y0zygbsHrYmanqqDF2Cm0m+59hNHR4eH",
	"d3YtzVnkzqptI2YzSQiwFeaPK2jnV2yMGQ+aZm2WMukFEA5xJjMmU+Qh0Qmo1CgNOyzLQo0190BTqvCd",
	"s/NLAqKr9WM5wUzJlPwkMKmc1XJmGTWgYTXrNQpdZZqcunB2rEusy6veL4ylr/S6xreBhcDL3QH4HohT",
	"FgOJytGPhhFpqrRw4X3RRZcnoDG1u7L/30rUy5UDqMbSWr+oe4UytbNo9PRoc9DuXitUzXG8rh+rOWGb",
	"+rolDcd4+f0h8XixmorphbiJynPhC/QTP+ZwyQxQ2d26n4DFYGb0wy/htZEVhXlUpf4dnbQf0K4mY+5N",
	"ENURHTJ4Rg2DGqfX1jpDltnZ79dVSX90S7aTTSNPwyJjYo3gdU3s9si+sUF1vcIT56bg9aKymlJn0Sia",
	"WVuY0ZCkOOA0N6Ek12rAioJmyv49AA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
