package e2ee

import (
	"bytes"
	"crypto/ecdh"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"testing"
)

var update = flag.Bool("update", false, "rewrite testdata/vectors.json")

const vectorsPath = "../../testdata/vectors.json"

// fixed derives deterministic test material from a label.
func fixed(label string, n int) []byte {
	var out []byte
	for i := 0; len(out) < n; i++ {
		h := sha256.Sum256([]byte{byte(i)})
		h = sha256.Sum256(append([]byte("duongondro test "+label+" "), h[:]...))
		out = append(out, h[:]...)
	}
	return out[:n]
}

func uuidOf(label string) UUID {
	var u UUID
	copy(u[:], fixed(label, 16))
	u[6] = u[6]&0x0f | 0x70 // version 7 bits, as the apps generate
	u[8] = u[8]&0x3f | 0x80
	return u
}

func p256(t *testing.T, label string) *ecdh.PrivateKey {
	t.Helper()
	k, err := ecdh.P256().NewPrivateKey(fixed(label, 32))
	if err != nil {
		t.Fatal(err)
	}
	return k
}

type hexBytes []byte

func (h hexBytes) MarshalJSON() ([]byte, error) { return json.Marshal(hex.EncodeToString(h)) }

// Vectors is the file format of testdata/vectors.json.
type Vectors struct {
	Note       string           `json:"note"`
	Inputs     map[string]any   `json:"inputs"`
	Derived    map[string]any   `json:"derived"`
	Session    map[string]any   `json:"session"`
	Wraps      []map[string]any `json:"wraps"`
	Statements []map[string]any `json:"statements"`
	Invite     map[string]any   `json:"invite"`
	Recovery   map[string]any   `json:"recovery"`
}

func uuidHex(u UUID) string { return hex.EncodeToString(u[:]) }

func build(t *testing.T) Vectors {
	practiceKey := fixed("practice key", 32)
	user := uuidOf("user")
	session := uuidOf("session")
	device := uuidOf("recipient device")
	identitySeed := fixed("identity seed", 32)
	identity := ed25519.NewKeyFromSeed(identitySeed)
	recipient := p256(t, "recipient device key")
	ephemeral := p256(t, "ephemeral key")
	nonce := fixed("nonce", NonceSize)
	recoverySecret := fixed("recovery secret", 16)
	inviteSecret := fixed("invite secret", 10)
	qrSecret := fixed("qr secret", 32)

	v := Vectors{
		Note: "Generated by `go test ./internal/e2ee -update` from docs/crypto.md. Byte strings are hex unless a field says otherwise. Fixed nonces and ephemeral keys exist only here.",
		Inputs: map[string]any{
			"practiceKey":      hexBytes(practiceKey),
			"user":             uuidHex(user),
			"session":          uuidHex(session),
			"recipientDevice":  uuidHex(device),
			"identitySeed":     hexBytes(identitySeed),
			"identityPublic":   hexBytes(identity.Public().(ed25519.PublicKey)),
			"recipientPrivate": hexBytes(recipient.Bytes()),
			"recipientPublic":  hexBytes(recipient.PublicKey().Bytes()),
			"ephemeralPrivate": hexBytes(ephemeral.Bytes()),
			"ephemeralPublic":  hexBytes(ephemeral.PublicKey().Bytes()),
			"nonce":            hexBytes(nonce),
			"recoverySecret":   hexBytes(recoverySecret),
			"inviteSecret":     hexBytes(inviteSecret),
			"qrSecret":         hexBytes(qrSecret),
			"keyVersion":       1,
		},
	}

	sealKey := SealKey(practiceKey, user)
	v.Derived = map[string]any{"sealKey": hexBytes(sealKey)}

	sessionJSON := []byte(`{"count":108,"day":"2026-10-05","practice":"dorje-sempa","start":1791176400000,"tz":"Europe/Amsterdam","updatedAt":1791180000000}`)
	sealed, err := SealSession(sealKey, session, user, 1, sessionJSON, nonce)
	if err != nil {
		t.Fatal(err)
	}
	v.Session = map[string]any{
		"json":   string(sessionJSON),
		"aad":    hexBytes(SessionAAD(session, user, 1)),
		"padded": hexBytes(Pad(sessionJSON)),
		"sealed": hexBytes(sealed),
	}

	for _, w := range []struct {
		name   string
		kind   WrapKind
		secret []byte
	}{
		{"practice key", KindPracticeKey, practiceKey},
		{"identity seed", KindIdentitySeed, identitySeed},
	} {
		aad := WrapAAD(user, 1, device, w.kind)
		epk, box, err := Wrap(recipient.PublicKey(), ephemeral, w.secret, aad, nonce)
		if err != nil {
			t.Fatal(err)
		}
		shared, _ := ephemeral.ECDH(recipient.PublicKey())
		selfShared, _ := recipient.ECDH(recipient.PublicKey())
		rpk := recipient.PublicKey().Bytes()
		v.Wraps = append(v.Wraps, map[string]any{
			"name":       w.name,
			"kind":       int(w.kind),
			"aad":        hexBytes(aad),
			"shared":     hexBytes(shared),
			"wrapKey":    hexBytes(wrapKey(shared, epk, rpk)),
			"epk":        hexBytes(epk),
			"box":        hexBytes(box),
			"signature":  hexBytes(SignWrap(identity, epk, box, aad, rpk)),
			"enrolTag":   hexBytes(EnrolTag(qrSecret, epk, box, aad, rpk)),
			"selfShared": hexBytes(selfShared),
			"selfTag":    hexBytes(SelfTag(selfShared, user, epk, box, aad, rpk)),
		})
	}

	statements := []struct {
		typ string
		v   any
	}{
		{TypeDeviceList, DeviceList{
			Devices:  []Device{{ID: uuidHex(device), PK: recipient.PublicKey().Bytes(), Tier: "hardware"}},
			IssuedAt: 1791176400000, User: uuidHex(user), Version: 1,
		}},
		{TypeStreak, Streak{Current: 42, Day: "2026-10-05", Deadline: 1791324000000, Longest: 61, Practice: "dorje-sempa", Seq: 7, User: uuidHex(user)}},
		{TypeInvite, Invite{ExpiresAt: 1791781200000, InviteID: "7K2MQ9XA", Inviter: uuidHex(user), InviterIdentityPk: Bytes(identity.Public().(ed25519.PublicKey))}},
	}
	for _, s := range statements {
		payload, err := Marshal(s.v)
		if err != nil {
			t.Fatal(err)
		}
		v.Statements = append(v.Statements, map[string]any{
			"type":      s.typ,
			"payload":   string(payload),
			"message":   hexBytes(StatementMessage(s.typ, payload)),
			"signature": hexBytes(SignStatement(identity, s.typ, payload)),
		})
	}

	auth, pin := InviteKeys(inviteSecret)
	v.Invite = map[string]any{
		"auth": hexBytes(auth),
		"pin":  hexBytes(pin),
		"mac":  hexBytes(InviteMAC(pin, identity.Public().(ed25519.PublicKey))),
	}

	rk := RecoveryKey(recoverySecret, user)
	rbox, err := SealRecovery(rk, user, KindPracticeKey, practiceKey, nonce)
	if err != nil {
		t.Fatal(err)
	}
	v.Recovery = map[string]any{
		"recoveryKey":             hexBytes(rk),
		"aad":                     hexBytes(RecoveryAAD(user, KindPracticeKey)),
		"practiceKeyBox":          hexBytes(rbox),
		"practiceKeyBoxSignature": hexBytes(SignRecoveryBox(identity, user, KindPracticeKey, rbox)),
	}
	return v
}

func TestVectors(t *testing.T) {
	v := build(t)
	got, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	got = append(got, '\n')
	if *update {
		if err := os.WriteFile(vectorsPath, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("%v (run with -update to create it)", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatal("testdata/vectors.json is stale; run go test ./internal/e2ee -update and review the diff")
	}
}

func TestRoundTrips(t *testing.T) {
	practiceKey := fixed("practice key", 32)
	user, session, device := uuidOf("user"), uuidOf("session"), uuidOf("recipient device")
	nonce := fixed("nonce", NonceSize)
	sealKey := SealKey(practiceKey, user)

	msg := []byte(`{"count":108}`)
	sealed, err := SealSession(sealKey, session, user, 1, msg, nonce)
	if err != nil {
		t.Fatal(err)
	}
	if len(sealed) != NonceSize+256+16 {
		t.Fatalf("padding: sealed length %d", len(sealed))
	}
	if pt, err := OpenSession(sealKey, session, user, 1, sealed); err != nil || !bytes.Equal(pt, msg) {
		t.Fatalf("open: %v %q", err, pt)
	}
	if _, err := OpenSession(sealKey, session, user, 2, sealed); err != ErrOpen {
		t.Fatalf("a blob must not open under another key version: %v", err)
	}
	other := uuidOf("other session")
	if _, err := OpenSession(sealKey, other, user, 1, sealed); err != ErrOpen {
		t.Fatalf("a blob must not move to another session: %v", err)
	}

	recipient, ephemeral := p256(t, "recipient device key"), p256(t, "ephemeral key")
	aad := WrapAAD(user, 1, device, KindPracticeKey)
	epk, box, err := Wrap(recipient.PublicKey(), ephemeral, practiceKey, aad, nonce)
	if err != nil {
		t.Fatal(err)
	}
	if got, err := Unwrap(recipient, epk, box, aad); err != nil || !bytes.Equal(got, practiceKey) {
		t.Fatalf("unwrap: %v", err)
	}
	if _, err := Unwrap(recipient, epk, box, WrapAAD(user, 1, device, KindShareKey)); err != ErrOpen {
		t.Fatalf("a wrap must not open as another kind: %v", err)
	}

	identity := ed25519.NewKeyFromSeed(fixed("identity seed", 32))
	sig := SignWrap(identity, epk, box, aad, recipient.PublicKey().Bytes())
	if !VerifyWrap(identity.Public().(ed25519.PublicKey), epk, box, aad, recipient.PublicKey().Bytes(), sig) {
		t.Fatal("wrap signature does not verify")
	}
	box[20] ^= 1
	if VerifyWrap(identity.Public().(ed25519.PublicKey), epk, box, aad, recipient.PublicKey().Bytes(), sig) {
		t.Fatal("a modified wrap must not verify")
	}
}

func TestParsePublicKey(t *testing.T) {
	good := p256(t, "recipient device key").PublicKey().Bytes()
	if _, err := ParsePublicKey(good); err != nil {
		t.Fatal(err)
	}
	if _, err := ParsePublicKey(good[:33]); err == nil {
		t.Fatal("compressed or short keys must be rejected")
	}
	bad := append([]byte{}, good...)
	bad[64] ^= 1
	if _, err := ParsePublicKey(bad); err == nil {
		t.Fatal("a point off the curve must be rejected")
	}
	if _, err := ParsePublicKey(make([]byte, 32)); err == nil {
		t.Fatal("a 32-byte Curve25519 key must be rejected")
	}
}

func TestPadding(t *testing.T) {
	for _, n := range []int{0, 1, 254, 255, 256, 600} {
		in := bytes.Repeat([]byte{'a'}, n)
		p := Pad(in)
		if len(p)%256 != 0 || len(p) < n+1 {
			t.Fatalf("pad %d → %d", n, len(p))
		}
		out, err := Unpad(p)
		if err != nil || !bytes.Equal(out, in) {
			t.Fatalf("unpad %d: %v", n, err)
		}
	}
	if _, err := Unpad(make([]byte, 256)); err != ErrPadding {
		t.Fatal("all-zero padding must fail")
	}
}
