// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id) VALUES ($1, $2)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users DEFAULT VALUES RETURNING id, identity_public_key, key_version, created_at
`

func (q *Queries) CreateUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, createUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityPublicKey,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.identity_public_key, users.key_version, users.created_at FROM sessions JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
`

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityPublicKey,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, identity_public_key, key_version, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityPublicKey,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const setIdentityKey = `-- name: SetIdentityKey :execrows
UPDATE users SET identity_public_key = $1
WHERE id = $2 AND identity_public_key IS NULL
`

type SetIdentityKeyParams struct {
	IdentityPublicKey []byte
	ID                uuid.UUID
}

// Set once: a second, different key is refused (the service reports a conflict).
func (q *Queries) SetIdentityKey(ctx context.Context, arg SetIdentityKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIdentityKey, arg.IdentityPublicKey, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
