// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admission.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const createAdmissionCode = `-- name: CreateAdmissionCode :exec
INSERT INTO admission_codes (code_hash, expires_at) VALUES ($1, $2)
`

type CreateAdmissionCodeParams struct {
	CodeHash  []byte    `json:"codeHash"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreateAdmissionCode(ctx context.Context, arg CreateAdmissionCodeParams) error {
	_, err := q.db.Exec(ctx, createAdmissionCode, arg.CodeHash, arg.ExpiresAt)
	return err
}

const exportAdmissionCodes = `-- name: ExportAdmissionCodes :many
SELECT created_at, expires_at, used_at FROM admission_codes WHERE used_by = $1 ORDER BY created_at
`

type ExportAdmissionCodesRow struct {
	CreatedAt time.Time  `json:"createdAt"`
	ExpiresAt time.Time  `json:"expiresAt"`
	UsedAt    *time.Time `json:"usedAt"`
}

func (q *Queries) ExportAdmissionCodes(ctx context.Context, usedBy *uuid.UUID) ([]ExportAdmissionCodesRow, error) {
	rows, err := q.db.Query(ctx, exportAdmissionCodes, usedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportAdmissionCodesRow
	for rows.Next() {
		var i ExportAdmissionCodesRow
		if err := rows.Scan(&i.CreatedAt, &i.ExpiresAt, &i.UsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveAdmissionCode = `-- name: GetLiveAdmissionCode :one
SELECT id, code_hash, created_at, expires_at, used_by, used_at FROM admission_codes WHERE code_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetLiveAdmissionCode(ctx context.Context, codeHash []byte) (AdmissionCode, error) {
	row := q.db.QueryRow(ctx, getLiveAdmissionCode, codeHash)
	var i AdmissionCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
	)
	return i, err
}

const lockAdmissionCode = `-- name: LockAdmissionCode :one
SELECT id, code_hash, created_at, expires_at, used_by, used_at FROM admission_codes WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAdmissionCode(ctx context.Context, id uuid.UUID) (AdmissionCode, error) {
	row := q.db.QueryRow(ctx, lockAdmissionCode, id)
	var i AdmissionCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
	)
	return i, err
}

const useAdmissionCode = `-- name: UseAdmissionCode :exec
UPDATE admission_codes SET used_by = $1, used_at = now() WHERE id = $2
`

type UseAdmissionCodeParams struct {
	UsedBy *uuid.UUID `json:"usedBy"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) UseAdmissionCode(ctx context.Context, arg UseAdmissionCodeParams) error {
	_, err := q.db.Exec(ctx, useAdmissionCode, arg.UsedBy, arg.ID)
	return err
}
