// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, public_key, tier) VALUES ($1, $2, $3)
ON CONFLICT (user_id, public_key) DO NOTHING
RETURNING id, user_id, public_key, tier, created_at
`

type CreateDeviceParams struct {
	UserID    uuid.UUID
	PublicKey []byte
	Tier      string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UserID, arg.PublicKey, arg.Tier)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, public_key, tier, created_at FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByKey = `-- name: GetDeviceByKey :one
SELECT id, user_id, public_key, tier, created_at FROM devices WHERE user_id = $1 AND public_key = $2
`

type GetDeviceByKeyParams struct {
	UserID    uuid.UUID
	PublicKey []byte
}

func (q *Queries) GetDeviceByKey(ctx context.Context, arg GetDeviceByKeyParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByKey, arg.UserID, arg.PublicKey)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.Tier,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceList = `-- name: GetDeviceList :one
SELECT user_id, version, payload, signature, updated_at FROM device_lists WHERE user_id = $1
`

func (q *Queries) GetDeviceList(ctx context.Context, userID uuid.UUID) (DeviceList, error) {
	row := q.db.QueryRow(ctx, getDeviceList, userID)
	var i DeviceList
	err := row.Scan(
		&i.UserID,
		&i.Version,
		&i.Payload,
		&i.Signature,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, user_id, public_key, tier, created_at FROM devices WHERE user_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListDevices(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.Tier,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putDeviceList = `-- name: PutDeviceList :execrows
INSERT INTO device_lists (user_id, version, payload, signature) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    version = EXCLUDED.version, payload = EXCLUDED.payload,
    signature = EXCLUDED.signature, updated_at = now()
WHERE device_lists.version < EXCLUDED.version
`

type PutDeviceListParams struct {
	UserID    uuid.UUID
	Version   int64
	Payload   []byte
	Signature []byte
}

// Only a higher version replaces the stored list.
func (q *Queries) PutDeviceList(ctx context.Context, arg PutDeviceListParams) (int64, error) {
	result, err := q.db.Exec(ctx, putDeviceList,
		arg.UserID,
		arg.Version,
		arg.Payload,
		arg.Signature,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
