// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package db

import (
	"context"
)

const countDownload = `-- name: CountDownload :exec
INSERT INTO downloads (platform, day, count) VALUES ($1, (now() AT TIME ZONE 'UTC')::date, 1)
ON CONFLICT (platform, day) DO UPDATE SET count = downloads.count + 1
`

// One more download today (UTC). A single statement, so concurrent requests
// never lose an increment.
func (q *Queries) CountDownload(ctx context.Context, platform string) error {
	_, err := q.db.Exec(ctx, countDownload, platform)
	return err
}

const downloadTotal = `-- name: DownloadTotal :one
SELECT coalesce(sum(count), 0)::bigint AS total FROM downloads WHERE platform = $1
`

func (q *Queries) DownloadTotal(ctx context.Context, platform string) (int64, error) {
	row := q.db.QueryRow(ctx, downloadTotal, platform)
	var total int64
	err := row.Scan(&total)
	return total, err
}
