// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gdpr.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const exportInviteNode = `-- name: ExportInviteNode :one
SELECT node_id, parent_id, created_at FROM invite_tree WHERE user_id = $1
`

type ExportInviteNodeRow struct {
	NodeID    uuid.UUID  `json:"nodeId"`
	ParentID  *uuid.UUID `json:"parentId"`
	CreatedAt time.Time  `json:"createdAt"`
}

func (q *Queries) ExportInviteNode(ctx context.Context, userID *uuid.UUID) (ExportInviteNodeRow, error) {
	row := q.db.QueryRow(ctx, exportInviteNode, userID)
	var i ExportInviteNodeRow
	err := row.Scan(&i.NodeID, &i.ParentID, &i.CreatedAt)
	return i, err
}

const exportLogs = `-- name: ExportLogs :many
SELECT id, user_id, sealed, key_version, client_updated_at, deleted_at, xid, created_at, updated_at FROM practice_logs WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ExportLogs(ctx context.Context, userID uuid.UUID) ([]PracticeLog, error) {
	rows, err := q.db.Query(ctx, exportLogs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PracticeLog
	for rows.Next() {
		var i PracticeLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Sealed,
			&i.KeyVersion,
			&i.ClientUpdatedAt,
			&i.DeletedAt,
			&i.Xid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportRedemptions = `-- name: ExportRedemptions :many
SELECT invite_id, invitee_id, payload, signature, created_at FROM invite_redemptions WHERE invitee_id = $1 ORDER BY created_at
`

func (q *Queries) ExportRedemptions(ctx context.Context, inviteeID uuid.UUID) ([]InviteRedemption, error) {
	rows, err := q.db.Query(ctx, exportRedemptions, inviteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InviteRedemption
	for rows.Next() {
		var i InviteRedemption
		if err := rows.Scan(
			&i.InviteID,
			&i.InviteeID,
			&i.Payload,
			&i.Signature,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportReports = `-- name: ExportReports :many
SELECT id, reported_id, reason, created_at FROM reports WHERE reporter_id = $1 ORDER BY created_at
`

type ExportReportsRow struct {
	ID         uuid.UUID  `json:"id"`
	ReportedID *uuid.UUID `json:"reportedId"`
	Reason     string     `json:"reason"`
	CreatedAt  time.Time  `json:"createdAt"`
}

func (q *Queries) ExportReports(ctx context.Context, reporterID uuid.UUID) ([]ExportReportsRow, error) {
	rows, err := q.db.Query(ctx, exportReports, reporterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportReportsRow
	for rows.Next() {
		var i ExportReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportedID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSessions = `-- name: ExportSessions :many

SELECT created_at FROM sessions WHERE user_id = $1 ORDER BY created_at
`

// Everything the server holds about one user, for GET /api/me/export. A new table
// needs a query here and a place in service.Export; internal/service's
// TestExportCoversEveryTable fails until it has one.
func (q *Queries) ExportSessions(ctx context.Context, userID uuid.UUID) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, exportSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var created_at time.Time
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportWraps = `-- name: ExportWraps :many
SELECT key_wraps.device_id, key_wraps.kind, key_wraps.key_version, key_wraps.ephemeral_key, key_wraps.box, key_wraps.auth_type, key_wraps.authenticator, key_wraps.created_at FROM key_wraps JOIN devices ON devices.id = key_wraps.device_id
WHERE devices.user_id = $1 ORDER BY key_wraps.device_id, key_wraps.kind, key_wraps.key_version
`

func (q *Queries) ExportWraps(ctx context.Context, userID uuid.UUID) ([]KeyWrap, error) {
	rows, err := q.db.Query(ctx, exportWraps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeyWrap
	for rows.Next() {
		var i KeyWrap
		if err := rows.Scan(
			&i.DeviceID,
			&i.Kind,
			&i.KeyVersion,
			&i.EphemeralKey,
			&i.Box,
			&i.AuthType,
			&i.Authenticator,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
