// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"uuid"
)

type AuthIdentity struct {
	Provider     string    `json:"provider"`
	Subject      string    `json:"subject"`
	UserID       uuid.UUID `json:"userId"`
	Email        *string   `json:"email"`
	RefreshToken *string   `json:"refreshToken"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Block struct {
	BlockerID uuid.UUID `json:"blockerId"`
	BlockedID uuid.UUID `json:"blockedId"`
	CreatedAt time.Time `json:"createdAt"`
}

type Credential struct {
	ID         []byte     `json:"id"`
	UserID     uuid.UUID  `json:"userId"`
	Data       []byte     `json:"data"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt"`
}

type DatabaseGeneration struct {
	Singleton bool      `json:"singleton"`
	ID        uuid.UUID `json:"id"`
}

type Device struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	PublicKey []byte    `json:"publicKey"`
	Tier      string    `json:"tier"`
	CreatedAt time.Time `json:"createdAt"`
}

type DeviceList struct {
	UserID    uuid.UUID `json:"userId"`
	Version   int64     `json:"version"`
	Payload   []byte    `json:"payload"`
	Signature []byte    `json:"signature"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Friendship struct {
	UserID    uuid.UUID `json:"userId"`
	FriendID  uuid.UUID `json:"friendId"`
	CreatedAt time.Time `json:"createdAt"`
}

type Invite struct {
	ID        string     `json:"id"`
	InviterID uuid.UUID  `json:"inviterId"`
	AuthHash  []byte     `json:"authHash"`
	Payload   []byte     `json:"payload"`
	Signature []byte     `json:"signature"`
	Mac       []byte     `json:"mac"`
	ExpiresAt time.Time  `json:"expiresAt"`
	RevokedAt *time.Time `json:"revokedAt"`
	CreatedAt time.Time  `json:"createdAt"`
}

type InviteRedemption struct {
	InviteID  string    `json:"inviteId"`
	InviteeID uuid.UUID `json:"inviteeId"`
	Payload   []byte    `json:"payload"`
	Signature []byte    `json:"signature"`
	CreatedAt time.Time `json:"createdAt"`
}

type InviteTree struct {
	NodeID    uuid.UUID  `json:"nodeId"`
	UserID    *uuid.UUID `json:"userId"`
	ParentID  *uuid.UUID `json:"parentId"`
	CreatedAt time.Time  `json:"createdAt"`
}

type KeyWrap struct {
	DeviceID      uuid.UUID `json:"deviceId"`
	Kind          int16     `json:"kind"`
	KeyVersion    int32     `json:"keyVersion"`
	EphemeralKey  []byte    `json:"ephemeralKey"`
	Box           []byte    `json:"box"`
	AuthType      string    `json:"authType"`
	Authenticator []byte    `json:"authenticator"`
	CreatedAt     time.Time `json:"createdAt"`
}

type MagicLink struct {
	TokenHash []byte    `json:"tokenHash"`
	Email     string    `json:"email"`
	InviteID  *string   `json:"inviteId"`
	CreatedAt time.Time `json:"createdAt"`
}

type PracticeLog struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"userId"`
	Sealed          []byte     `json:"sealed"`
	KeyVersion      int32      `json:"keyVersion"`
	ClientUpdatedAt time.Time  `json:"clientUpdatedAt"`
	DeletedAt       *time.Time `json:"deletedAt"`
	Xid             uint64     `json:"xid"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
}

type RecoveryBox struct {
	UserID    uuid.UUID `json:"userId"`
	Kind      int16     `json:"kind"`
	Box       []byte    `json:"box"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Report struct {
	ID         uuid.UUID `json:"id"`
	ReporterID uuid.UUID `json:"reporterId"`
	ReportedID uuid.UUID `json:"reportedId"`
	Reason     string    `json:"reason"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Session struct {
	TokenHash []byte    `json:"tokenHash"`
	UserID    uuid.UUID `json:"userId"`
	CreatedAt time.Time `json:"createdAt"`
}

type Streak struct {
	UserID     uuid.UUID `json:"userId"`
	Practice   string    `json:"practice"`
	Seq        int64     `json:"seq"`
	Payload    []byte    `json:"payload"`
	Signature  []byte    `json:"signature"`
	DeadlineAt time.Time `json:"deadlineAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	IdentityPublicKey []byte    `json:"identityPublicKey"`
	KeyVersion        int32     `json:"keyVersion"`
	CreatedAt         time.Time `json:"createdAt"`
	DisplayName       string    `json:"displayName"`
}

type WebauthnSession struct {
	ID        uuid.UUID  `json:"id"`
	Data      []byte     `json:"data"`
	UserID    *uuid.UUID `json:"userId"`
	InviteID  *string    `json:"inviteId"`
	CreatedAt time.Time  `json:"createdAt"`
}
