// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"uuid"
)

type DatabaseGeneration struct {
	Singleton bool
	ID        uuid.UUID
}

type Device struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PublicKey []byte
	Tier      string
	CreatedAt time.Time
}

type DeviceList struct {
	UserID    uuid.UUID
	Version   int64
	Payload   []byte
	Signature []byte
	UpdatedAt time.Time
}

type KeyWrap struct {
	DeviceID      uuid.UUID
	Kind          int16
	KeyVersion    int32
	EphemeralKey  []byte
	Box           []byte
	AuthType      string
	Authenticator []byte
	CreatedAt     time.Time
}

type PracticeLog struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Sealed          []byte
	KeyVersion      int32
	ClientUpdatedAt time.Time
	DeletedAt       *time.Time
	Xid             uint64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RecoveryBox struct {
	UserID    uuid.UUID
	Kind      int16
	Box       []byte
	UpdatedAt time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID                uuid.UUID
	IdentityPublicKey []byte
	KeyVersion        int32
	CreatedAt         time.Time
}
