// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const deletePushToken = `-- name: DeletePushToken :execrows
DELETE FROM push_tokens WHERE device_id = $1
`

func (q *Queries) DeletePushToken(ctx context.Context, deviceID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushToken, deviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const doneTodayRecipients = `-- name: DoneTodayRecipients :many
SELECT user_id FROM friendships WHERE friend_id = $1 AND notify_done
`

// Friends who asked to hear when this user practises, and are not blocked either way
// (a block removes the friendship, so this is the friendship alone).
func (q *Queries) DoneTodayRecipients(ctx context.Context, friendID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, doneTodayRecipients, friendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dropPushToken = `-- name: DropPushToken :exec
DELETE FROM push_tokens WHERE platform = $1 AND token = $2
`

type DropPushTokenParams struct {
	Platform string `json:"platform"`
	Token    string `json:"token"`
}

// The provider reported the token unregistered.
func (q *Queries) DropPushToken(ctx context.Context, arg DropPushTokenParams) error {
	_, err := q.db.Exec(ctx, dropPushToken, arg.Platform, arg.Token)
	return err
}

const exportNudges = `-- name: ExportNudges :many
SELECT sender_id, recipient_id, day, created_at FROM nudges WHERE sender_id = $1 OR recipient_id = $1 ORDER BY created_at
`

func (q *Queries) ExportNudges(ctx context.Context, senderID uuid.UUID) ([]Nudge, error) {
	rows, err := q.db.Query(ctx, exportNudges, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nudge
	for rows.Next() {
		var i Nudge
		if err := rows.Scan(
			&i.SenderID,
			&i.RecipientID,
			&i.Day,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPushTokens = `-- name: ExportPushTokens :many
SELECT push_tokens.device_id, push_tokens.platform, push_tokens.updated_at FROM push_tokens
JOIN devices ON devices.id = push_tokens.device_id WHERE devices.user_id = $1
`

type ExportPushTokensRow struct {
	DeviceID  uuid.UUID `json:"deviceId"`
	Platform  string    `json:"platform"`
	UpdatedAt time.Time `json:"updatedAt"`
}

func (q *Queries) ExportPushTokens(ctx context.Context, userID uuid.UUID) ([]ExportPushTokensRow, error) {
	rows, err := q.db.Query(ctx, exportPushTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportPushTokensRow
	for rows.Next() {
		var i ExportPushTokensRow
		if err := rows.Scan(&i.DeviceID, &i.Platform, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAtRiskSent = `-- name: MarkAtRiskSent :exec
UPDATE streaks SET at_risk_sent_seq = $3 WHERE user_id = $1 AND practice = $2 AND seq = $3
`

type MarkAtRiskSentParams struct {
	UserID        uuid.UUID `json:"userId"`
	Practice      string    `json:"practice"`
	AtRiskSentSeq int64     `json:"atRiskSentSeq"`
}

func (q *Queries) MarkAtRiskSent(ctx context.Context, arg MarkAtRiskSentParams) error {
	_, err := q.db.Exec(ctx, markAtRiskSent, arg.UserID, arg.Practice, arg.AtRiskSentSeq)
	return err
}

const pushTokensOf = `-- name: PushTokensOf :many
SELECT push_tokens.device_id, push_tokens.platform, push_tokens.token, push_tokens.updated_at FROM push_tokens JOIN devices ON devices.id = push_tokens.device_id
WHERE devices.user_id = $1
`

func (q *Queries) PushTokensOf(ctx context.Context, userID uuid.UUID) ([]PushToken, error) {
	rows, err := q.db.Query(ctx, pushTokensOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushToken
	for rows.Next() {
		var i PushToken
		if err := rows.Scan(
			&i.DeviceID,
			&i.Platform,
			&i.Token,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putPushToken = `-- name: PutPushToken :exec
INSERT INTO push_tokens (device_id, platform, token) VALUES ($1, $2, $3)
ON CONFLICT (device_id) DO UPDATE SET platform = EXCLUDED.platform, token = EXCLUDED.token, updated_at = now()
`

type PutPushTokenParams struct {
	DeviceID uuid.UUID `json:"deviceId"`
	Platform string    `json:"platform"`
	Token    string    `json:"token"`
}

func (q *Queries) PutPushToken(ctx context.Context, arg PutPushTokenParams) error {
	_, err := q.db.Exec(ctx, putPushToken, arg.DeviceID, arg.Platform, arg.Token)
	return err
}

const recordNudge = `-- name: RecordNudge :execrows
INSERT INTO nudges (sender_id, recipient_id, day) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type RecordNudgeParams struct {
	SenderID    uuid.UUID `json:"senderId"`
	RecipientID uuid.UUID `json:"recipientId"`
	Day         time.Time `json:"day"`
}

func (q *Queries) RecordNudge(ctx context.Context, arg RecordNudgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordNudge, arg.SenderID, arg.RecipientID, arg.Day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releasePushToken = `-- name: ReleasePushToken :exec
DELETE FROM push_tokens WHERE platform = $1 AND token = $2 AND device_id <> $3
`

type ReleasePushTokenParams struct {
	Platform string    `json:"platform"`
	Token    string    `json:"token"`
	DeviceID uuid.UUID `json:"deviceId"`
}

// A token reaches one device: drop it from any other before storing it.
func (q *Queries) ReleasePushToken(ctx context.Context, arg ReleasePushTokenParams) error {
	_, err := q.db.Exec(ctx, releasePushToken, arg.Platform, arg.Token, arg.DeviceID)
	return err
}

const setNotifyDone = `-- name: SetNotifyDone :execrows
UPDATE friendships SET notify_done = $3 WHERE user_id = $1 AND friend_id = $2
`

type SetNotifyDoneParams struct {
	UserID     uuid.UUID `json:"userId"`
	FriendID   uuid.UUID `json:"friendId"`
	NotifyDone bool      `json:"notifyDone"`
}

func (q *Queries) SetNotifyDone(ctx context.Context, arg SetNotifyDoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNotifyDone, arg.UserID, arg.FriendID, arg.NotifyDone)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const streaksAtRisk = `-- name: StreaksAtRisk :many
SELECT user_id, practice, seq, payload, signature, deadline_at, updated_at, at_risk_sent_seq FROM streaks
WHERE deadline_at > now() AND deadline_at <= now() + interval '2 hours' AND at_risk_sent_seq < seq
ORDER BY deadline_at
LIMIT 500
`

// Public streaks whose deadline is under two hours away, not yet nudged for this
// statement, and still alive.
func (q *Queries) StreaksAtRisk(ctx context.Context) ([]Streak, error) {
	rows, err := q.db.Query(ctx, streaksAtRisk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Streak
	for rows.Next() {
		var i Streak
		if err := rows.Scan(
			&i.UserID,
			&i.Practice,
			&i.Seq,
			&i.Payload,
			&i.Signature,
			&i.DeadlineAt,
			&i.UpdatedAt,
			&i.AtRiskSentSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
