// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package db

import (
	"context"

	"uuid"
)

const listRecoveryBoxes = `-- name: ListRecoveryBoxes :many
SELECT user_id, kind, box, updated_at FROM recovery_boxes WHERE user_id = $1 ORDER BY kind
`

func (q *Queries) ListRecoveryBoxes(ctx context.Context, userID uuid.UUID) ([]RecoveryBox, error) {
	rows, err := q.db.Query(ctx, listRecoveryBoxes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoveryBox
	for rows.Next() {
		var i RecoveryBox
		if err := rows.Scan(
			&i.UserID,
			&i.Kind,
			&i.Box,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putRecoveryBox = `-- name: PutRecoveryBox :exec
INSERT INTO recovery_boxes (user_id, kind, box) VALUES ($1, $2, $3)
ON CONFLICT (user_id, kind) DO UPDATE SET box = EXCLUDED.box, updated_at = now()
`

type PutRecoveryBoxParams struct {
	UserID uuid.UUID `json:"userId"`
	Kind   int16     `json:"kind"`
	Box    []byte    `json:"box"`
}

func (q *Queries) PutRecoveryBox(ctx context.Context, arg PutRecoveryBoxParams) error {
	_, err := q.db.Exec(ctx, putRecoveryBox, arg.UserID, arg.Kind, arg.Box)
	return err
}
