// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signin.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :one
DELETE FROM magic_links
WHERE token_hash = $1 AND created_at > now() - interval '15 minutes'
RETURNING token_hash, email, invite_id, created_at, admission_id, code_hash, wrong_codes, code_dead_at
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, tokenHash []byte) (MagicLink, error) {
	row := q.db.QueryRow(ctx, consumeMagicLink, tokenHash)
	var i MagicLink
	err := row.Scan(
		&i.TokenHash,
		&i.Email,
		&i.InviteID,
		&i.CreatedAt,
		&i.AdmissionID,
		&i.CodeHash,
		&i.WrongCodes,
		&i.CodeDeadAt,
	)
	return i, err
}

const consumeNonce = `-- name: ConsumeNonce :execrows
DELETE FROM auth_nonces WHERE nonce_hash = $1 AND created_at > now() - interval '10 minutes'
`

func (q *Queries) ConsumeNonce(ctx context.Context, nonceHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, consumeNonce, nonceHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeWebauthnSession = `-- name: ConsumeWebauthnSession :one
DELETE FROM webauthn_sessions WHERE id = $1 AND created_at > now() - interval '5 minutes'
RETURNING id, data, user_id, invite_id, created_at, admission_id
`

func (q *Queries) ConsumeWebauthnSession(ctx context.Context, id uuid.UUID) (WebauthnSession, error) {
	row := q.db.QueryRow(ctx, consumeWebauthnSession, id)
	var i WebauthnSession
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.UserID,
		&i.InviteID,
		&i.CreatedAt,
		&i.AdmissionID,
	)
	return i, err
}

const countRecentMagicLinks = `-- name: CountRecentMagicLinks :one
SELECT count(*) FROM magic_links WHERE lower(email) = lower($1) AND created_at > now() - interval '15 minutes'
`

func (q *Queries) CountRecentMagicLinks(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentMagicLinks, lower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (id, user_id, data) VALUES ($1, $2, $3)
`

type CreateCredentialParams struct {
	ID     []byte    `json:"id"`
	UserID uuid.UUID `json:"userId"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential, arg.ID, arg.UserID, arg.Data)
	return err
}

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO auth_identities (provider, subject, user_id, email, refresh_token) VALUES ($1, $2, $3, $4, $5)
`

type CreateIdentityParams struct {
	Provider     string    `json:"provider"`
	Subject      string    `json:"subject"`
	UserID       uuid.UUID `json:"userId"`
	Email        *string   `json:"email"`
	RefreshToken *string   `json:"refreshToken"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.Provider,
		arg.Subject,
		arg.UserID,
		arg.Email,
		arg.RefreshToken,
	)
	return err
}

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links (token_hash, email, invite_id, admission_id, code_hash) VALUES ($1, $2, $3, $4, $5)
`

type CreateMagicLinkParams struct {
	TokenHash   []byte     `json:"tokenHash"`
	Email       string     `json:"email"`
	InviteID    *string    `json:"inviteId"`
	AdmissionID *uuid.UUID `json:"admissionId"`
	CodeHash    []byte     `json:"codeHash"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.Exec(ctx, createMagicLink,
		arg.TokenHash,
		arg.Email,
		arg.InviteID,
		arg.AdmissionID,
		arg.CodeHash,
	)
	return err
}

const createNonce = `-- name: CreateNonce :exec
INSERT INTO auth_nonces (nonce_hash) VALUES ($1)
`

func (q *Queries) CreateNonce(ctx context.Context, nonceHash []byte) error {
	_, err := q.db.Exec(ctx, createNonce, nonceHash)
	return err
}

const createUserWithID = `-- name: CreateUserWithID :one
INSERT INTO users (id) VALUES ($1) RETURNING id, identity_public_key, key_version, created_at, display_name, username, gender
`

func (q *Queries) CreateUserWithID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityPublicKey,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Username,
		&i.Gender,
	)
	return i, err
}

const createWebauthnSession = `-- name: CreateWebauthnSession :one
INSERT INTO webauthn_sessions (data, user_id, invite_id, admission_id) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateWebauthnSessionParams struct {
	Data        []byte     `json:"data"`
	UserID      *uuid.UUID `json:"userId"`
	InviteID    *string    `json:"inviteId"`
	AdmissionID *uuid.UUID `json:"admissionId"`
}

func (q *Queries) CreateWebauthnSession(ctx context.Context, arg CreateWebauthnSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createWebauthnSession,
		arg.Data,
		arg.UserID,
		arg.InviteID,
		arg.AdmissionID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteMagicLink = `-- name: DeleteMagicLink :exec
DELETE FROM magic_links WHERE token_hash = $1
`

func (q *Queries) DeleteMagicLink(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteMagicLink, tokenHash)
	return err
}

const deleteMagicLinksForUser = `-- name: DeleteMagicLinksForUser :exec
DELETE FROM magic_links WHERE lower(email) IN (
    SELECT lower(auth_identities.email) FROM auth_identities
    WHERE auth_identities.user_id = $1 AND auth_identities.email IS NOT NULL)
`

// A purge also drops unused links to the user's addresses.
func (q *Queries) DeleteMagicLinksForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMagicLinksForUser, userID)
	return err
}

const deleteWebauthnSessionsForUser = `-- name: DeleteWebauthnSessionsForUser :exec
DELETE FROM webauthn_sessions WHERE user_id = $1
`

func (q *Queries) DeleteWebauthnSessionsForUser(ctx context.Context, userID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebauthnSessionsForUser, userID)
	return err
}

const exportCredentials = `-- name: ExportCredentials :many
SELECT id, created_at, last_used_at FROM credentials WHERE user_id = $1 ORDER BY created_at
`

type ExportCredentialsRow struct {
	ID         []byte     `json:"id"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt"`
}

func (q *Queries) ExportCredentials(ctx context.Context, userID uuid.UUID) ([]ExportCredentialsRow, error) {
	rows, err := q.db.Query(ctx, exportCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportCredentialsRow
	for rows.Next() {
		var i ExportCredentialsRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.LastUsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportIdentities = `-- name: ExportIdentities :many
SELECT provider, subject, email, created_at FROM auth_identities WHERE user_id = $1 ORDER BY created_at
`

type ExportIdentitiesRow struct {
	Provider  string    `json:"provider"`
	Subject   string    `json:"subject"`
	Email     *string   `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) ExportIdentities(ctx context.Context, userID uuid.UUID) ([]ExportIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, exportIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportIdentitiesRow
	for rows.Next() {
		var i ExportIdentitiesRow
		if err := rows.Scan(
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportMagicLinks = `-- name: ExportMagicLinks :many
SELECT magic_links.email, magic_links.created_at FROM magic_links
WHERE lower(magic_links.email) IN (
    SELECT lower(auth_identities.email) FROM auth_identities
    WHERE auth_identities.user_id = $1 AND auth_identities.email IS NOT NULL)
`

type ExportMagicLinksRow struct {
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}

func (q *Queries) ExportMagicLinks(ctx context.Context, userID uuid.UUID) ([]ExportMagicLinksRow, error) {
	rows, err := q.db.Query(ctx, exportMagicLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportMagicLinksRow
	for rows.Next() {
		var i ExportMagicLinksRow
		if err := rows.Scan(&i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentity = `-- name: GetIdentity :one
SELECT provider, subject, user_id, email, refresh_token, created_at FROM auth_identities WHERE provider = $1 AND subject = $2
`

type GetIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.Subject)
	var i AuthIdentity
	err := row.Scan(
		&i.Provider,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.RefreshToken,
		&i.CreatedAt,
	)
	return i, err
}

const inviterOf = `-- name: InviterOf :one
SELECT inviter_id FROM invites WHERE id = $1
`

func (q *Queries) InviterOf(ctx context.Context, id string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, inviterOf, id)
	var inviter_id uuid.UUID
	err := row.Scan(&inviter_id)
	return inviter_id, err
}

const killMagicLinkCodes = `-- name: KillMagicLinkCodes :exec
UPDATE magic_links SET code_dead_at = now() WHERE lower(email) = lower($1) AND code_dead_at IS NULL
`

// A newer mail to the address makes the older codes unusable; their links still work.
func (q *Queries) KillMagicLinkCodes(ctx context.Context, lower string) error {
	_, err := q.db.Exec(ctx, killMagicLinkCodes, lower)
	return err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, user_id, data, created_at, last_used_at FROM credentials WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListCredentials(ctx context.Context, userID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Data,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentities = `-- name: ListIdentities :many
SELECT provider, subject, user_id, email, refresh_token, created_at FROM auth_identities WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListIdentities(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthIdentity
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.Provider,
			&i.Subject,
			&i.UserID,
			&i.Email,
			&i.RefreshToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEmail = `-- name: LockEmail :exec
SELECT pg_advisory_xact_lock(hashtextextended(lower($1::text), 0))
`

// Serialises magic-link requests for one address, so the per-address limit holds.
func (q *Queries) LockEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, lockEmail, email)
	return err
}

const lockLiveMagicLinkForEmail = `-- name: LockLiveMagicLinkForEmail :one
SELECT token_hash, email, invite_id, created_at, admission_id, code_hash, wrong_codes, code_dead_at FROM magic_links
WHERE lower(email) = lower($1) AND code_dead_at IS NULL AND code_hash IS NOT NULL
    AND created_at > now() - interval '15 minutes'
ORDER BY created_at DESC LIMIT 1
FOR UPDATE
`

// The one live code to an address (a newer mail kills the older), for a typed code.
func (q *Queries) LockLiveMagicLinkForEmail(ctx context.Context, lower string) (MagicLink, error) {
	row := q.db.QueryRow(ctx, lockLiveMagicLinkForEmail, lower)
	var i MagicLink
	err := row.Scan(
		&i.TokenHash,
		&i.Email,
		&i.InviteID,
		&i.CreatedAt,
		&i.AdmissionID,
		&i.CodeHash,
		&i.WrongCodes,
		&i.CodeDeadAt,
	)
	return i, err
}

const purgeExpiredMagicLinks = `-- name: PurgeExpiredMagicLinks :execrows
DELETE FROM magic_links WHERE created_at <= now() - interval '15 minutes'
`

func (q *Queries) PurgeExpiredMagicLinks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredMagicLinks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredNonces = `-- name: PurgeExpiredNonces :exec
DELETE FROM auth_nonces WHERE created_at <= now() - interval '10 minutes'
`

func (q *Queries) PurgeExpiredNonces(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeExpiredNonces)
	return err
}

const purgeExpiredWebauthnSessions = `-- name: PurgeExpiredWebauthnSessions :execrows
DELETE FROM webauthn_sessions WHERE created_at <= now() - interval '5 minutes'
`

func (q *Queries) PurgeExpiredWebauthnSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredWebauthnSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWrongMagicLinkCode = `-- name: RecordWrongMagicLinkCode :exec
UPDATE magic_links SET wrong_codes = wrong_codes + 1,
    code_dead_at = CASE WHEN wrong_codes + 1 >= $1::smallint THEN now() ELSE code_dead_at END
WHERE token_hash = $2
`

type RecordWrongMagicLinkCodeParams struct {
	MaxWrong  int16  `json:"maxWrong"`
	TokenHash []byte `json:"tokenHash"`
}

// The fifth wrong code kills the code; the link still works.
func (q *Queries) RecordWrongMagicLinkCode(ctx context.Context, arg RecordWrongMagicLinkCodeParams) error {
	_, err := q.db.Exec(ctx, recordWrongMagicLinkCode, arg.MaxWrong, arg.TokenHash)
	return err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials SET data = $2, last_used_at = now() WHERE id = $1
`

type UpdateCredentialParams struct {
	ID   []byte `json:"id"`
	Data []byte `json:"data"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential, arg.ID, arg.Data)
	return err
}

const updateIdentity = `-- name: UpdateIdentity :exec
UPDATE auth_identities SET email = COALESCE($1, email),
    refresh_token = COALESCE($2, refresh_token)
WHERE provider = $3 AND subject = $4
`

type UpdateIdentityParams struct {
	Email        *string `json:"email"`
	RefreshToken *string `json:"refreshToken"`
	Provider     string  `json:"provider"`
	Subject      string  `json:"subject"`
}

func (q *Queries) UpdateIdentity(ctx context.Context, arg UpdateIdentityParams) error {
	_, err := q.db.Exec(ctx, updateIdentity,
		arg.Email,
		arg.RefreshToken,
		arg.Provider,
		arg.Subject,
	)
	return err
}
