// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const areFriends = `-- name: AreFriends :one
SELECT EXISTS (SELECT 1 FROM friendships WHERE user_id = $1 AND friend_id = $2)
`

type AreFriendsParams struct {
	UserID   uuid.UUID `json:"userId"`
	FriendID uuid.UUID `json:"friendId"`
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.UserID, arg.FriendID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const befriend = `-- name: Befriend :exec
INSERT INTO friendships (user_id, friend_id) VALUES ($1, $2), ($2, $1)
ON CONFLICT DO NOTHING
`

type BefriendParams struct {
	UserID   uuid.UUID `json:"userId"`
	FriendID uuid.UUID `json:"friendId"`
}

func (q *Queries) Befriend(ctx context.Context, arg BefriendParams) error {
	_, err := q.db.Exec(ctx, befriend, arg.UserID, arg.FriendID)
	return err
}

const block = `-- name: Block :exec
INSERT INTO blocks (blocker_id, blocked_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type BlockParams struct {
	BlockerID uuid.UUID `json:"blockerId"`
	BlockedID uuid.UUID `json:"blockedId"`
}

func (q *Queries) Block(ctx context.Context, arg BlockParams) error {
	_, err := q.db.Exec(ctx, block, arg.BlockerID, arg.BlockedID)
	return err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (id, inviter_id, auth_hash, payload, signature, mac, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateInviteParams struct {
	ID        string    `json:"id"`
	InviterID uuid.UUID `json:"inviterId"`
	AuthHash  []byte    `json:"authHash"`
	Payload   []byte    `json:"payload"`
	Signature []byte    `json:"signature"`
	Mac       []byte    `json:"mac"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.Exec(ctx, createInvite,
		arg.ID,
		arg.InviterID,
		arg.AuthHash,
		arg.Payload,
		arg.Signature,
		arg.Mac,
		arg.ExpiresAt,
	)
	return err
}

const createInviteNode = `-- name: CreateInviteNode :exec
INSERT INTO invite_tree (user_id, parent_id)
VALUES ($1, (SELECT node_id FROM invite_tree WHERE invite_tree.user_id = $2))
`

type CreateInviteNodeParams struct {
	UserID    *uuid.UUID `json:"userId"`
	InviterID *uuid.UUID `json:"inviterId"`
}

// Every account gets a node; parent_id is the inviter's node (NULL for the first
// members and DEV accounts).
func (q *Queries) CreateInviteNode(ctx context.Context, arg CreateInviteNodeParams) error {
	_, err := q.db.Exec(ctx, createInviteNode, arg.UserID, arg.InviterID)
	return err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, reported_id, reason) VALUES ($1, $2, $3) RETURNING id
`

type CreateReportParams struct {
	ReporterID uuid.UUID `json:"reporterId"`
	ReportedID uuid.UUID `json:"reportedId"`
	Reason     string    `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createReport, arg.ReporterID, arg.ReportedID, arg.Reason)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteStreak = `-- name: DeleteStreak :execrows
DELETE FROM streaks WHERE user_id = $1 AND practice = $2
`

type DeleteStreakParams struct {
	UserID   uuid.UUID `json:"userId"`
	Practice string    `json:"practice"`
}

func (q *Queries) DeleteStreak(ctx context.Context, arg DeleteStreakParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStreak, arg.UserID, arg.Practice)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const friendsStreaks = `-- name: FriendsStreaks :many
SELECT streaks.user_id, streaks.practice, streaks.seq, streaks.payload, streaks.signature, streaks.deadline_at, streaks.updated_at FROM streaks
JOIN friendships ON friendships.friend_id = streaks.user_id
WHERE friendships.user_id = $1
ORDER BY streaks.user_id, streaks.practice
`

func (q *Queries) FriendsStreaks(ctx context.Context, userID uuid.UUID) ([]Streak, error) {
	rows, err := q.db.Query(ctx, friendsStreaks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Streak
	for rows.Next() {
		var i Streak
		if err := rows.Scan(
			&i.UserID,
			&i.Practice,
			&i.Seq,
			&i.Payload,
			&i.Signature,
			&i.DeadlineAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveInvite = `-- name: GetLiveInvite :one
SELECT id, inviter_id, auth_hash, payload, signature, mac, expires_at, revoked_at, created_at FROM invites WHERE id = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetLiveInvite(ctx context.Context, id string) (Invite, error) {
	row := q.db.QueryRow(ctx, getLiveInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.InviterID,
		&i.AuthHash,
		&i.Payload,
		&i.Signature,
		&i.Mac,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const isBlockedEitherWay = `-- name: IsBlockedEitherWay :one
SELECT EXISTS (
    SELECT 1 FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2) OR (blocker_id = $2 AND blocked_id = $1))
`

type IsBlockedEitherWayParams struct {
	BlockerID uuid.UUID `json:"blockerId"`
	BlockedID uuid.UUID `json:"blockedId"`
}

func (q *Queries) IsBlockedEitherWay(ctx context.Context, arg IsBlockedEitherWayParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEitherWay, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlocks = `-- name: ListBlocks :many
SELECT blocker_id, blocked_id, created_at FROM blocks WHERE blocker_id = $1 ORDER BY created_at
`

func (q *Queries) ListBlocks(ctx context.Context, blockerID uuid.UUID) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocks, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(&i.BlockerID, &i.BlockedID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT users.id, users.display_name, users.identity_public_key, friendships.created_at
FROM friendships JOIN users ON users.id = friendships.friend_id
WHERE friendships.user_id = $1
ORDER BY friendships.created_at, users.id
`

type ListFriendsRow struct {
	ID                uuid.UUID `json:"id"`
	DisplayName       string    `json:"displayName"`
	IdentityPublicKey []byte    `json:"identityPublicKey"`
	CreatedAt         time.Time `json:"createdAt"`
}

func (q *Queries) ListFriends(ctx context.Context, userID uuid.UUID) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsRow
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.IdentityPublicKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, inviter_id, auth_hash, payload, signature, mac, expires_at, revoked_at, created_at FROM invites WHERE inviter_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context, inviterID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites, inviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.InviterID,
			&i.AuthHash,
			&i.Payload,
			&i.Signature,
			&i.Mac,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownStreaks = `-- name: OwnStreaks :many
SELECT user_id, practice, seq, payload, signature, deadline_at, updated_at FROM streaks WHERE user_id = $1 ORDER BY practice
`

func (q *Queries) OwnStreaks(ctx context.Context, userID uuid.UUID) ([]Streak, error) {
	rows, err := q.db.Query(ctx, ownStreaks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Streak
	for rows.Next() {
		var i Streak
		if err := rows.Scan(
			&i.UserID,
			&i.Practice,
			&i.Seq,
			&i.Payload,
			&i.Signature,
			&i.DeadlineAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putStreak = `-- name: PutStreak :execrows
INSERT INTO streaks (user_id, practice, seq, payload, signature, deadline_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, practice) DO UPDATE SET
    seq = EXCLUDED.seq, payload = EXCLUDED.payload, signature = EXCLUDED.signature,
    deadline_at = EXCLUDED.deadline_at, updated_at = now()
WHERE streaks.seq < EXCLUDED.seq
`

type PutStreakParams struct {
	UserID     uuid.UUID `json:"userId"`
	Practice   string    `json:"practice"`
	Seq        int64     `json:"seq"`
	Payload    []byte    `json:"payload"`
	Signature  []byte    `json:"signature"`
	DeadlineAt time.Time `json:"deadlineAt"`
}

// Only a higher seq replaces the stored statement.
func (q *Queries) PutStreak(ctx context.Context, arg PutStreakParams) (int64, error) {
	result, err := q.db.Exec(ctx, putStreak,
		arg.UserID,
		arg.Practice,
		arg.Seq,
		arg.Payload,
		arg.Signature,
		arg.DeadlineAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordRedemption = `-- name: RecordRedemption :exec
INSERT INTO invite_redemptions (invite_id, invitee_id, payload, signature) VALUES ($1, $2, $3, $4)
ON CONFLICT (invite_id, invitee_id) DO NOTHING
`

type RecordRedemptionParams struct {
	InviteID  string    `json:"inviteId"`
	InviteeID uuid.UUID `json:"inviteeId"`
	Payload   []byte    `json:"payload"`
	Signature []byte    `json:"signature"`
}

func (q *Queries) RecordRedemption(ctx context.Context, arg RecordRedemptionParams) error {
	_, err := q.db.Exec(ctx, recordRedemption,
		arg.InviteID,
		arg.InviteeID,
		arg.Payload,
		arg.Signature,
	)
	return err
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invites SET revoked_at = now() WHERE id = $1 AND inviter_id = $2 AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	ID        string    `json:"id"`
	InviterID uuid.UUID `json:"inviterId"`
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.InviterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDisplayName = `-- name: SetDisplayName :exec
UPDATE users SET display_name = $2 WHERE id = $1
`

type SetDisplayNameParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"displayName"`
}

func (q *Queries) SetDisplayName(ctx context.Context, arg SetDisplayNameParams) error {
	_, err := q.db.Exec(ctx, setDisplayName, arg.ID, arg.DisplayName)
	return err
}

const unblock = `-- name: Unblock :execrows
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockParams struct {
	BlockerID uuid.UUID `json:"blockerId"`
	BlockedID uuid.UUID `json:"blockedId"`
}

func (q *Queries) Unblock(ctx context.Context, arg UnblockParams) (int64, error) {
	result, err := q.db.Exec(ctx, unblock, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfriend = `-- name: Unfriend :execrows
DELETE FROM friendships WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
`

type UnfriendParams struct {
	UserID   uuid.UUID `json:"userId"`
	FriendID uuid.UUID `json:"friendId"`
}

func (q *Queries) Unfriend(ctx context.Context, arg UnfriendParams) (int64, error) {
	result, err := q.db.Exec(ctx, unfriend, arg.UserID, arg.FriendID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
