// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const getLog = `-- name: GetLog :one
SELECT id, user_id, sealed, key_version, client_updated_at, deleted_at, xid, created_at, updated_at FROM practice_logs WHERE id = $1
`

func (q *Queries) GetLog(ctx context.Context, id uuid.UUID) (PracticeLog, error) {
	row := q.db.QueryRow(ctx, getLog, id)
	var i PracticeLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sealed,
		&i.KeyVersion,
		&i.ClientUpdatedAt,
		&i.DeletedAt,
		&i.Xid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logsChangedSince = `-- name: LogsChangedSince :many
SELECT id, user_id, sealed, key_version, client_updated_at, deleted_at, xid, created_at, updated_at FROM practice_logs
WHERE user_id = $1 AND xid >= $2::xid8
ORDER BY xid, id
`

type LogsChangedSinceParams struct {
	UserID uuid.UUID
	Since  uint64
}

func (q *Queries) LogsChangedSince(ctx context.Context, arg LogsChangedSinceParams) ([]PracticeLog, error) {
	rows, err := q.db.Query(ctx, logsChangedSince, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PracticeLog
	for rows.Next() {
		var i PracticeLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Sealed,
			&i.KeyVersion,
			&i.ClientUpdatedAt,
			&i.DeletedAt,
			&i.Xid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotXmin = `-- name: SnapshotXmin :one
SELECT pg_snapshot_xmin(pg_current_snapshot())::xid8 AS xmin
`

func (q *Queries) SnapshotXmin(ctx context.Context) (uint64, error) {
	row := q.db.QueryRow(ctx, snapshotXmin)
	var xmin uint64
	err := row.Scan(&xmin)
	return xmin, err
}

const syncState = `-- name: SyncState :one
SELECT database_generation.id AS generation, pg_snapshot_xmax(pg_current_snapshot())::xid8 AS xmax
FROM database_generation
`

type SyncStateRow struct {
	Generation uuid.UUID
	Xmax       uint64
}

func (q *Queries) SyncState(ctx context.Context) (SyncStateRow, error) {
	row := q.db.QueryRow(ctx, syncState)
	var i SyncStateRow
	err := row.Scan(&i.Generation, &i.Xmax)
	return i, err
}

const upsertLog = `-- name: UpsertLog :one
INSERT INTO practice_logs (id, user_id, sealed, key_version, client_updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    sealed = EXCLUDED.sealed, key_version = EXCLUDED.key_version,
    client_updated_at = EXCLUDED.client_updated_at, deleted_at = EXCLUDED.deleted_at,
    xid = pg_current_xact_id(), updated_at = now()
WHERE practice_logs.user_id = EXCLUDED.user_id
  AND practice_logs.client_updated_at < EXCLUDED.client_updated_at
RETURNING id, user_id, sealed, key_version, client_updated_at, deleted_at, xid, created_at, updated_at
`

type UpsertLogParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Sealed          []byte
	KeyVersion      int32
	ClientUpdatedAt time.Time
	DeletedAt       *time.Time
}

// Last write wins on the client's clock. A row of another user is never touched:
// the WHERE fails, nothing returns, and the service answers 404.
func (q *Queries) UpsertLog(ctx context.Context, arg UpsertLogParams) (PracticeLog, error) {
	row := q.db.QueryRow(ctx, upsertLog,
		arg.ID,
		arg.UserID,
		arg.Sealed,
		arg.KeyVersion,
		arg.ClientUpdatedAt,
		arg.DeletedAt,
	)
	var i PracticeLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sealed,
		&i.KeyVersion,
		&i.ClientUpdatedAt,
		&i.DeletedAt,
		&i.Xid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
