// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wraps.sql

package db

import (
	"context"

	"uuid"
)

const listWraps = `-- name: ListWraps :many
SELECT device_id, kind, key_version, ephemeral_key, box, auth_type, authenticator, created_at FROM key_wraps WHERE device_id = $1 ORDER BY kind, key_version
`

func (q *Queries) ListWraps(ctx context.Context, deviceID uuid.UUID) ([]KeyWrap, error) {
	rows, err := q.db.Query(ctx, listWraps, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeyWrap
	for rows.Next() {
		var i KeyWrap
		if err := rows.Scan(
			&i.DeviceID,
			&i.Kind,
			&i.KeyVersion,
			&i.EphemeralKey,
			&i.Box,
			&i.AuthType,
			&i.Authenticator,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id, identity_public_key, key_version, created_at, display_name, username, gender FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IdentityPublicKey,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Username,
		&i.Gender,
	)
	return i, err
}

const practiceKeyHolders = `-- name: PracticeKeyHolders :many
SELECT devices.id, devices.public_key FROM devices
JOIN key_wraps ON key_wraps.device_id = devices.id
WHERE devices.user_id = $1 AND key_wraps.kind = 1 AND key_wraps.key_version = $2
ORDER BY devices.id
`

type PracticeKeyHoldersParams struct {
	UserID     uuid.UUID `json:"userId"`
	KeyVersion int32     `json:"keyVersion"`
}

type PracticeKeyHoldersRow struct {
	ID        uuid.UUID `json:"id"`
	PublicKey []byte    `json:"publicKey"`
}

// Devices holding a wrap of the given practice-key version: a rotation must wrap the
// new key to exactly these.
func (q *Queries) PracticeKeyHolders(ctx context.Context, arg PracticeKeyHoldersParams) ([]PracticeKeyHoldersRow, error) {
	rows, err := q.db.Query(ctx, practiceKeyHolders, arg.UserID, arg.KeyVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PracticeKeyHoldersRow
	for rows.Next() {
		var i PracticeKeyHoldersRow
		if err := rows.Scan(&i.ID, &i.PublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putWrap = `-- name: PutWrap :exec
INSERT INTO key_wraps (device_id, kind, key_version, ephemeral_key, box, auth_type, authenticator)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (device_id, kind, key_version) DO UPDATE SET
    ephemeral_key = EXCLUDED.ephemeral_key, box = EXCLUDED.box,
    auth_type = EXCLUDED.auth_type, authenticator = EXCLUDED.authenticator, created_at = now()
`

type PutWrapParams struct {
	DeviceID      uuid.UUID `json:"deviceId"`
	Kind          int16     `json:"kind"`
	KeyVersion    int32     `json:"keyVersion"`
	EphemeralKey  []byte    `json:"ephemeralKey"`
	Box           []byte    `json:"box"`
	AuthType      string    `json:"authType"`
	Authenticator []byte    `json:"authenticator"`
}

func (q *Queries) PutWrap(ctx context.Context, arg PutWrapParams) error {
	_, err := q.db.Exec(ctx, putWrap,
		arg.DeviceID,
		arg.Kind,
		arg.KeyVersion,
		arg.EphemeralKey,
		arg.Box,
		arg.AuthType,
		arg.Authenticator,
	)
	return err
}

const setKeyVersion = `-- name: SetKeyVersion :execrows
UPDATE users SET key_version = $1
WHERE id = $2 AND key_version = $1::integer - 1
`

type SetKeyVersionParams struct {
	NewVersion int32     `json:"newVersion"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) SetKeyVersion(ctx context.Context, arg SetKeyVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setKeyVersion, arg.NewVersion, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
